import { v } from 'convex/values';
import {
  mutation,
  query,
  action,
  internalQuery,
  internalMutation,
  internalAction,
  type ActionCtx,
} from './_generated/server';
import { getAuthCaller, type AuthenticatedCaller } from './lib/getAuthCaller';
import { isSuperadmin } from './lib/auth';
import { internal } from './_generated/api';
import type { Doc, Id } from './_generated/dataModel';
import { DEFAULT_LIST_CAP } from './lib/limits';
import { notify } from './lib/notify';
import { getStartingLeaveBalances } from './lib/leaveBalances';
import { resolveOrgUnitsByName } from './lib/orgUnits';
import {
  getTravelAllowancePolicy,
  resolveTravelAllowance,
  resolveTravelAllowanceForOrg,
} from './lib/travelAllowance';
import { assertModuleAccess } from './lib/entitlements';

const providerValidator = v.union(
  v.literal('lucky_carrot'),
  v.literal('imid'),
  v.literal('armsoft'),
  v.literal('telegram'),
);

type Provider = 'lucky_carrot' | 'imid' | 'armsoft' | 'telegram';

/** Credential fields that must never reach the client. */
const SECRET_FIELDS = ['apiKey', 'clientSecret', 'apiPassword', 'botToken'] as const;

/**
 * Server-only cache fields. Unlike SECRET_FIELDS these are not user-editable,
 * so they are stripped entirely rather than masked.
 *
 * `webhookSecret` belongs here rather than in SECRET_FIELDS: it is generated by
 * `rotateWebhookSecret` and shown to the admin exactly once, so there is no
 * "leave blank to keep" edit flow that would need a mask.
 */
const SERVER_ONLY_FIELDS = ['imidAccessToken', 'imidTokenExpiresAt', 'webhookSecret'] as const;

/** Placeholder sent to the client in place of a stored secret. */
export const SECRET_MASK = '••••••••';

/** Upper bound on employees pulled from a provider in a single sync run. */
const MAX_IMPORT_RECORDS = 2000;

/** Employees upserted per mutation — keeps each transaction small. */
const UPSERT_BATCH_SIZE = 25;

/**
 * Pages followed in one sync run. A backstop against a provider whose next
 * link never terminates; `MAX_IMPORT_RECORDS` bounds the data, this bounds the
 * request count.
 */
const MAX_IMPORT_PAGES = 50;

/** Roles that a provider sync must never create, modify or deactivate. */
const PRIVILEGED_ROLES = new Set(['superadmin', 'admin', 'supervisor']);

/**
 * Only org admins may see or change integration settings — these configs hold
 * third-party credentials.
 */
function canAdminOrg(caller: AuthenticatedCaller, organizationId: Id<'organizations'>) {
  if (isSuperadmin(caller)) return true;
  return caller.role === 'admin' && caller.organizationId === organizationId;
}

/**
 * Replace stored secrets with a mask so the UI can show "a value is set"
 * without ever transmitting the credential itself, and drop server-only caches.
 */
function maskConfig(doc: Doc<'integrationConfigs'>) {
  const config: Record<string, unknown> = { ...doc.config };
  for (const field of SECRET_FIELDS) {
    if (config[field]) config[field] = SECRET_MASK;
  }
  // Whether a webhook secret exists is not itself sensitive, and the UI needs it
  // to distinguish "not set up yet" from "rotate the existing one". It rides
  // inside `config` because that is the only object the UI reads fields from.
  const hasWebhookSecret = !!doc.config.webhookSecret;
  for (const field of SERVER_ONLY_FIELDS) {
    delete config[field];
  }
  config.hasWebhookSecret = hasWebhookSecret;
  return {
    ...doc,
    config: config as Doc<'integrationConfigs'>['config'] & { hasWebhookSecret: boolean },
  };
}

// ── Get integration config for an organization (masked) ────────────────────
export const getIntegrationConfig = query({
  args: { organizationId: v.id('organizations'), provider: providerValidator },
  handler: async (ctx, { organizationId, provider }) => {
    const caller = await getAuthCaller(ctx);
    if (!caller || !canAdminOrg(caller, organizationId)) return null;

    const doc = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', provider),
      )
      .first();

    return doc ? maskConfig(doc) : null;
  },
});

// ── Get all integration configs for an organization (masked) ───────────────
export const getAllIntegrationConfigs = query({
  args: { organizationId: v.id('organizations') },
  handler: async (ctx, { organizationId }) => {
    const caller = await getAuthCaller(ctx);
    if (!caller || !canAdminOrg(caller, organizationId)) return [];

    const docs = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org', (q) => q.eq('organizationId', organizationId))
      .take(10);

    return docs.map(maskConfig);
  },
});

// ── Internal: read the raw config (secrets intact) for server-side syncing ──
export const getIntegrationConfigInternal = internalQuery({
  args: { organizationId: v.id('organizations'), provider: providerValidator },
  handler: async (ctx, { organizationId, provider }) => {
    return await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', provider),
      )
      .first();
  },
});

// ── Internal: record sync progress without re-sending the whole config ──────
export const setSyncState = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
    syncStatus: v.union(
      v.literal('idle'),
      v.literal('syncing'),
      v.literal('error'),
      v.literal('success'),
    ),
    lastError: v.optional(v.string()),
    lastSyncAt: v.optional(v.number()),
  },
  handler: async (ctx, { organizationId, provider, syncStatus, lastError, lastSyncAt }) => {
    const existing = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', provider),
      )
      .first();
    if (!existing) return;

    await ctx.db.patch(existing._id, {
      config: {
        ...existing.config,
        syncStatus,
        lastError,
        ...(lastSyncAt ? { lastSyncAt } : {}),
      },
      updatedAt: Date.now(),
    });
  },
});

// ── Internal: cache an OAuth token so every sync doesn't re-authenticate ────
export const cacheImidToken = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    accessToken: v.string(),
    expiresAt: v.number(),
  },
  handler: async (ctx, { organizationId, accessToken, expiresAt }) => {
    const existing = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'imid'),
      )
      .first();
    if (!existing) return;

    await ctx.db.patch(existing._id, {
      config: {
        ...existing.config,
        imidAccessToken: accessToken,
        imidTokenExpiresAt: expiresAt,
      },
      updatedAt: Date.now(),
    });
  },
});

// ── Save/update integration config ────────────────────────────────────────
export const saveIntegrationConfig = mutation({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
    config: v.object({
      isEnabled: v.boolean(),
      lastSyncAt: v.optional(v.number()),
      syncStatus: v.optional(
        v.union(v.literal('idle'), v.literal('syncing'), v.literal('error'), v.literal('success')),
      ),
      lastError: v.optional(v.string()),
      apiKey: v.optional(v.string()),
      apiUrl: v.optional(v.string()),
      webhookUrl: v.optional(v.string()),
      autoSyncEmployees: v.optional(v.boolean()),
      webhookEnabled: v.optional(v.boolean()),
      clientId: v.optional(v.string()),
      clientSecret: v.optional(v.string()),
      redirectUri: v.optional(v.string()),
      enableLogin: v.optional(v.boolean()),
      enableSigning: v.optional(v.boolean()),
      enableVerification: v.optional(v.boolean()),
      authorizePath: v.optional(v.string()),
      userInfoPath: v.optional(v.string()),
      signingPath: v.optional(v.string()),
      apiEndpoint: v.optional(v.string()),
      apiUsername: v.optional(v.string()),
      apiPassword: v.optional(v.string()),
      syncEmployees: v.optional(v.boolean()),
      syncPayroll: v.optional(v.boolean()),
      syncSchedule: v.optional(v.string()),
      employeesPath: v.optional(v.string()),
      employeesListKey: v.optional(v.string()),
      fieldMap: v.optional(v.string()),
      deactivateMissing: v.optional(v.boolean()),
      tokenPath: v.optional(v.string()),
      // Telegram
      botToken: v.optional(v.string()),
      botUsername: v.optional(v.string()),
    }),
    /** Secret field names to erase. Sent when an admin removes a credential. */
    clearSecrets: v.optional(v.array(v.string())),
  },
  handler: async (ctx, { organizationId, provider, config, clearSecrets }) => {
    await assertModuleAccess(ctx, 'integrations');
    const caller = await getAuthCaller(ctx);
    if (!caller) throw new Error('Not authenticated');
    if (!canAdminOrg(caller, organizationId)) {
      throw new Error('Only admins of this organization can configure integrations');
    }

    // Reject a malformed field map at save time rather than mid-sync.
    if (config.fieldMap) {
      let parsed: unknown;
      try {
        parsed = JSON.parse(config.fieldMap);
      } catch {
        throw new Error('Field mapping must be valid JSON');
      }
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        throw new Error('Field mapping must be a JSON object of ourField → providerField');
      }
      for (const value of Object.values(parsed as Record<string, unknown>)) {
        if (typeof value !== 'string') {
          throw new Error('Field mapping values must be strings');
        }
      }
    }

    if (config.syncSchedule && !isValidCronExpression(config.syncSchedule)) {
      throw new Error('Sync schedule must be a 5-field cron expression, e.g. "0 3 * * *"');
    }

    // A masked secret means "unchanged" — never persist the placeholder.
    const incoming: Record<string, unknown> = { ...config };
    for (const field of SECRET_FIELDS) {
      if (incoming[field] === SECRET_MASK) delete incoming[field];
    }

    const existing = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', provider),
      )
      .first();

    const now = Date.now();
    if (existing) {
      // Merge with existing config to preserve fields not sent
      const merged: Record<string, unknown> = { ...existing.config, ...incoming };

      // Explicit removal — only ever applied to real credential fields.
      for (const field of clearSecrets ?? []) {
        if ((SECRET_FIELDS as readonly string[]).includes(field)) {
          delete merged[field];
        }
      }
      // Dropping imID credentials must invalidate the cached token with them.
      if (
        (clearSecrets ?? []).includes('clientSecret') ||
        incoming.clientSecret !== undefined ||
        incoming.clientId !== undefined
      ) {
        delete merged.imidAccessToken;
        delete merged.imidTokenExpiresAt;
      }

      await ctx.db.patch(existing._id, {
        config: merged as Doc<'integrationConfigs'>['config'],
        updatedAt: now,
      });
    } else {
      await ctx.db.insert('integrationConfigs', {
        organizationId,
        provider,
        config: incoming as Doc<'integrationConfigs'>['config'],
        createdBy: caller._id,
        createdAt: now,
        updatedAt: now,
      });
    }

    // Audit log
    await ctx.db.insert('auditLogs', {
      organizationId,
      userId: caller._id,
      action: `integration_${provider}_updated`,
      target: provider,
      details: JSON.stringify({
        isEnabled: config.isEnabled,
        clearedSecrets: clearSecrets ?? [],
      }),
      createdAt: now,
    });
  },
});

/** Result of a sync attempt, whether admin-triggered or scheduled. */
type SyncResult = { success: boolean; message?: string; error?: string };

// ── Sync integration data (action - runs externally) ──────────────────────
export const syncIntegration = action({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
  },
  // Annotated explicitly: the handler reaches back into `internal.integrations`
  // for authorization, and without it TS cannot break that inference cycle.
  handler: async (ctx, { organizationId, provider }): Promise<SyncResult> => {
    // Actions have no db access, so authorize via an internal query.
    const caller: { userId: Id<'users'> } | null = await ctx.runQuery(
      internal.integrations.assertCanSync,
      { organizationId },
    );
    if (!caller) {
      return { success: false, error: 'Not authorized to sync this integration' };
    }

    return await runSync(ctx, organizationId, provider, caller.userId);
  },
});

/**
 * Shared sync body for both the admin-triggered action and the cron sweep.
 * `triggeredBy` is undefined for scheduled runs.
 */
function toError(error: unknown): Error {
  return error instanceof Error ? error : new Error(String(error));
}

async function runSync(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  provider: Provider,
  triggeredBy?: Id<'users'>,
): Promise<SyncResult> {
  // Read the raw config (with secrets) — never the masked public query.
  const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
    organizationId,
    provider,
  });

  if (!config || !config.config.isEnabled) {
    return { success: false, error: 'Integration not configured or disabled' };
  }

  await ctx.runMutation(internal.integrations.setSyncState, {
    organizationId,
    provider,
    syncStatus: 'syncing',
  });

  try {
    const result = await performSync(ctx, organizationId, provider, config.config);

    await ctx.runMutation(internal.integrations.logSync, {
      organizationId,
      provider,
      action: 'sync',
      status: result.skippedSync ? 'skipped' : 'success',
      message: result.message,
      created: result.created,
      updated: result.updated,
      deactivated: result.deactivated,
      skipped: result.skipped,
      details: result.details,
      triggeredBy,
    });

    await ctx.runMutation(internal.integrations.setSyncState, {
      organizationId,
      provider,
      // A skipped run imported nothing, so it must not read as "Connected" in
      // the UI, and `lastSyncAt` must keep pointing at the last real import.
      syncStatus: result.skippedSync ? 'idle' : 'success',
      ...(result.skippedSync ? {} : { lastSyncAt: Date.now() }),
      // Clear any stale error from a previous failed run.
      lastError: undefined,
    });

    return { success: true, message: result.message };
  } catch (error: unknown) {
    const message = toError(error).message;

    await ctx.runMutation(internal.integrations.logSync, {
      organizationId,
      provider,
      action: 'sync',
      status: 'error',
      message,
      triggeredBy,
    });

    await ctx.runMutation(internal.integrations.setSyncState, {
      organizationId,
      provider,
      syncStatus: 'error',
      lastError: message,
    });

    return { success: false, error: message };
  }
}

// ── Internal: check the caller may sync this org's integrations ─────────────
export const assertCanSync = internalQuery({
  args: { organizationId: v.id('organizations') },
  handler: async (ctx, { organizationId }) => {
    const caller = await getAuthCaller(ctx);
    if (!caller || !canAdminOrg(caller, organizationId)) return null;
    return { userId: caller._id };
  },
});

// ── Log a sync event (internal — written only by the sync action) ───────────
export const logSync = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
    action: v.string(),
    status: v.union(v.literal('success'), v.literal('error'), v.literal('skipped')),
    message: v.string(),
    details: v.optional(v.string()),
    created: v.optional(v.number()),
    updated: v.optional(v.number()),
    deactivated: v.optional(v.number()),
    skipped: v.optional(v.number()),
    triggeredBy: v.optional(v.id('users')),
  },
  handler: async (ctx, args) => {
    await ctx.db.insert('integrationSyncLogs', {
      ...args,
      createdAt: Date.now(),
    });
  },
});

// ── Get sync logs ─────────────────────────────────────────────────────────
export const getSyncLogs = query({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
  },
  handler: async (ctx, { organizationId, provider }) => {
    const caller = await getAuthCaller(ctx);
    if (!caller || !canAdminOrg(caller, organizationId)) return [];

    return await ctx.db
      .query('integrationSyncLogs')
      .withIndex('by_org_provider_created', (q) =>
        q.eq('organizationId', organizationId).eq('provider', provider),
      )
      .order('desc')
      .take(50);
  },
});

// ═══════════════════════════════════════════════════════════════════════════
// EMPLOYEE UPSERT — the write half of a sync
// ═══════════════════════════════════════════════════════════════════════════

const incomingEmployeeValidator = v.object({
  email: v.string(),
  name: v.string(),
  department: v.optional(v.string()),
  position: v.optional(v.string()),
  phone: v.optional(v.string()),
  location: v.optional(v.string()),
  employeeType: v.optional(v.union(v.literal('staff'), v.literal('contractor'))),
  isActive: v.optional(v.boolean()),
  externalId: v.optional(v.string()),
});

/**
 * Create or update employees pulled from a provider.
 *
 * Guard rails:
 *  - never creates or modifies privileged roles (admin/supervisor/superadmin);
 *  - scoped to the organization by email, so an address belonging to another
 *    tenant is skipped rather than hijacked;
 *  - respects the organization's seat limit, same as manual employee creation.
 */
export const upsertEmployeeBatch = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    provider: providerValidator,
    employees: v.array(incomingEmployeeValidator),
  },
  handler: async (ctx, { organizationId, provider, employees }) => {
    const org = await ctx.db.get(organizationId);
    if (!org) throw new Error('Organization not found');

    let created = 0;
    let updated = 0;
    let skipped = 0;
    const notes: string[] = [];

    // Seat accounting is done once per batch, then tracked locally as we insert.
    const activeUsersRaw = await ctx.db
      .query('users')
      .withIndex('by_org_active', (q) =>
        q.eq('organizationId', organizationId).eq('isActive', true),
      )
      .take(DEFAULT_LIST_CAP + 1);
    const isCappedActiveUsers = activeUsersRaw.length > DEFAULT_LIST_CAP;
    void isCappedActiveUsers;
    const activeUsers = activeUsersRaw.slice(0, DEFAULT_LIST_CAP);
    let seatsUsed = activeUsers.length;

    // Read the org's travel allowance policy once — it is the same for every
    // employee in this batch, so resolving it inside the loop would cost one
    // extra database read per row.
    const travelPolicy = await getTravelAllowancePolicy(ctx, organizationId);

    for (const incoming of employees) {
      const email = incoming.email.toLowerCase().trim();
      if (!email || !email.includes('@')) {
        skipped++;
        notes.push(`invalid email: ${incoming.email.slice(0, 40)}`);
        continue;
      }

      // Scope the lookup to this org so we can detect a cross-tenant collision.
      let inOrg = await ctx.db
        .query('users')
        .withIndex('by_org_email', (q) => q.eq('organizationId', organizationId).eq('email', email))
        .first();

      // No email match, but the provider gave us an id we have seen before:
      // this is someone whose address changed at the source. Update them
      // rather than creating a second account for the same person.
      if (!inOrg && incoming.externalId) {
        inOrg = await ctx.db
          .query('users')
          .withIndex('by_org_external', (q) =>
            q
              .eq('organizationId', organizationId)
              .eq('externalSource', provider)
              .eq('externalId', incoming.externalId),
          )
          .first();
      }

      if (inOrg) {
        if (PRIVILEGED_ROLES.has(inOrg.role)) {
          skipped++;
          notes.push(`${email}: privileged role not managed by sync`);
          continue;
        }
        const patch: Record<string, unknown> = {
          name: incoming.name || inOrg.name,
          updatedAt: Date.now(),
        };
        // Remember the provider id so the next run can still find this person
        // if their address changes at the source.
        if (incoming.externalId) {
          patch.externalId = incoming.externalId;
          patch.externalSource = provider;
        }
        // Matched by provider id, not by email — the address changed upstream.
        // Only follow it if nobody else holds the new one.
        if (inOrg.email !== email) {
          const taken = await ctx.db
            .query('users')
            .withIndex('by_email', (q) => q.eq('email', email))
            .first();
          if (taken) {
            skipped++;
            notes.push(`${email}: address already belongs to another account`);
            continue;
          }
          patch.email = email;
        }
        // Only overwrite what the provider actually sent.
        if (incoming.department !== undefined || incoming.position !== undefined) {
          // Keep the id link in step with the denormalized name, otherwise the
          // employee drops out of department head-counts.
          const units = await resolveOrgUnitsByName(
            ctx,
            organizationId,
            { department: incoming.department, position: incoming.position },
            { create: true },
          );
          Object.assign(patch, units);
        }
        if (incoming.phone !== undefined) patch.phone = incoming.phone;
        if (incoming.location !== undefined) patch.location = incoming.location;
        if (incoming.employeeType !== undefined) patch.employeeType = incoming.employeeType;
        if (incoming.isActive !== undefined) {
          // Re-activating consumes a seat.
          if (incoming.isActive && !inOrg.isActive && seatsUsed >= org.employeeLimit) {
            skipped++;
            notes.push(`${email}: seat limit reached`);
            continue;
          }
          if (incoming.isActive && !inOrg.isActive) seatsUsed++;
          if (!incoming.isActive && inOrg.isActive) seatsUsed--;
          patch.isActive = incoming.isActive;
        }
        await ctx.db.patch(inOrg._id, patch);
        updated++;
        continue;
      }

      // Email owned by a different organization — never move or overwrite it.
      const elsewhere = await ctx.db
        .query('users')
        .withIndex('by_email', (q) => q.eq('email', email))
        .first();
      if (elsewhere) {
        skipped++;
        notes.push(`${email}: belongs to another organization`);
        continue;
      }

      if (seatsUsed >= org.employeeLimit) {
        skipped++;
        notes.push(`${email}: seat limit reached (${org.employeeLimit})`);
        continue;
      }

      const employeeType = incoming.employeeType ?? 'staff';
      const now = Date.now();
      const units = await resolveOrgUnitsByName(
        ctx,
        organizationId,
        { department: incoming.department, position: incoming.position },
        { create: true },
      );
      const balances = await getStartingLeaveBalances(ctx, organizationId);

      await ctx.db.insert('users', {
        organizationId,
        name: incoming.name || email,
        email,
        // No usable password — the account is claimed via the reset-password flow.
        passwordHash: '',
        role: 'employee',
        employeeType,
        ...units,
        phone: incoming.phone,
        location: incoming.location,
        // Recorded on creation so a later email change at the provider is a
        // match rather than a duplicate account.
        externalId: incoming.externalId,
        externalSource: incoming.externalId ? provider : undefined,
        isActive: incoming.isActive ?? true,
        isApproved: true,
        travelAllowance: resolveTravelAllowance(travelPolicy, employeeType),
        ...balances,
        createdAt: now,
      });
      if (incoming.isActive ?? true) seatsUsed++;
      created++;
    }

    return { created, updated, skipped, notes };
  },
});

/**
 * Deactivate synced employees the provider no longer lists. Opt-in via the
 * `deactivateMissing` config flag — off by default because a truncated or
 * partial provider response would otherwise lock people out.
 */
export const deactivateMissingEmployees = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    activeEmails: v.array(v.string()),
  },
  handler: async (ctx, { organizationId, activeEmails }) => {
    const keep = new Set(activeEmails.map((e) => e.toLowerCase().trim()));

    const orgUsersRaw = await ctx.db
      .query('users')
      .withIndex('by_org_active', (q) =>
        q.eq('organizationId', organizationId).eq('isActive', true),
      )
      .take(DEFAULT_LIST_CAP + 1);
    const isCappedOrgUsers = orgUsersRaw.length > DEFAULT_LIST_CAP;
    void isCappedOrgUsers;
    const orgUsers = orgUsersRaw.slice(0, DEFAULT_LIST_CAP);

    let deactivated = 0;
    for (const user of orgUsers) {
      if (PRIVILEGED_ROLES.has(user.role)) continue;
      if (keep.has(user.email.toLowerCase())) continue;
      await ctx.db.patch(user._id, { isActive: false, updatedAt: Date.now() });
      deactivated++;
    }
    return { deactivated };
  },
});

// ═══════════════════════════════════════════════════════════════════════════
// PROVIDER RESPONSE PARSING
// ═══════════════════════════════════════════════════════════════════════════

/** Read a possibly-nested value by dot path, e.g. "data.items". */
function readPath(source: unknown, path: string): unknown {
  return path.split('.').reduce<unknown>((acc, key) => {
    if (acc && typeof acc === 'object') return (acc as Record<string, unknown>)[key];
    return undefined;
  }, source);
}

/** Keys providers commonly wrap a collection in, tried in order. */
const LIST_KEY_CANDIDATES = [
  'data',
  'items',
  'employees',
  'results',
  'records',
  'users',
  'value',
  'data.items',
  'data.employees',
  'result.items',
];

/**
 * Pull the employee array out of a provider response. An explicit
 * `employeesListKey` wins; otherwise probe the shapes we've seen in the wild.
 */
export function extractList(payload: unknown, listKey?: string): unknown[] {
  if (listKey) {
    const picked = readPath(payload, listKey);
    if (!Array.isArray(picked)) {
      throw new Error(`Response has no array at "${listKey}"`);
    }
    return picked;
  }
  if (Array.isArray(payload)) return payload;
  for (const candidate of LIST_KEY_CANDIDATES) {
    const picked = readPath(payload, candidate);
    if (Array.isArray(picked)) return picked;
  }
  throw new Error(
    'Could not find an employee array in the response — set "Employees list key" to the field holding it',
  );
}

/** Keys providers commonly put a "next page" link or cursor under. */
const NEXT_PAGE_KEYS = [
  'next',
  'nextUrl',
  'next_url',
  'nextPage',
  'next_page',
  'nextLink',
  '@odata.nextLink',
  'paging.next',
  'pagination.next',
  'links.next',
  'meta.next',
  'meta.nextPage',
];

/**
 * Find the next page of a paginated employee response.
 *
 * A next link is provider-controlled data, so it is only honoured when it
 * resolves to the same origin as the page we just fetched — otherwise a
 * compromised or misconfigured provider could walk the sync onto an arbitrary
 * host, carrying the Authorization header with it. Relative links ("?page=2")
 * are resolved against the current URL; anything else is ignored, which simply
 * ends pagination rather than failing the run.
 */
export function findNextPageUrl(payload: unknown, currentUrl: string): string | undefined {
  for (const key of NEXT_PAGE_KEYS) {
    const raw = readPath(payload, key);
    // A `next: null`/`false` from an exhausted provider means stop, not "try
    // the next candidate key" — but only settle on keys that were present.
    if (raw === undefined) continue;
    if (raw === null || raw === '' || raw === false) return undefined;
    if (typeof raw !== 'string') continue;

    let candidate: URL;
    try {
      candidate = new URL(raw, currentUrl);
    } catch {
      return undefined;
    }
    if (candidate.origin !== new URL(currentUrl).origin) return undefined;
    if (candidate.protocol !== 'https:') return undefined;
    // A link back to the page we are on would loop forever.
    if (candidate.toString() === currentUrl) return undefined;
    return candidate.toString();
  }
  return undefined;
}

/** Provider field names we try for each of our fields, in priority order. */
const DEFAULT_FIELD_CANDIDATES: Record<string, string[]> = {
  email: ['email', 'work_email', 'workEmail', 'mail', 'emailAddress', 'email_address', 'userEmail'],
  name: ['name', 'full_name', 'fullName', 'displayName', 'display_name'],
  firstName: ['first_name', 'firstName', 'givenName', 'given_name'],
  lastName: ['last_name', 'lastName', 'surname', 'familyName', 'family_name'],
  department: ['department', 'department_name', 'departmentName', 'dept', 'division'],
  position: ['position', 'title', 'job_title', 'jobTitle', 'role_name', 'positionName'],
  phone: ['phone', 'phone_number', 'phoneNumber', 'mobile', 'telephone'],
  location: ['location', 'office', 'city', 'site'],
  employeeType: ['employee_type', 'employeeType', 'employment_type', 'contract_type'],
  isActive: ['is_active', 'isActive', 'active', 'enabled'],
  externalId: ['id', 'employee_id', 'employeeId', 'external_id', 'externalId', 'uuid'],
};

function pick(record: Record<string, unknown>, ourField: string, map: Record<string, string>) {
  // An explicit mapping is authoritative — no fallback guessing behind it.
  const mapped = map[ourField];
  if (mapped) return readPath(record, mapped);
  for (const candidate of DEFAULT_FIELD_CANDIDATES[ourField] ?? []) {
    const value = record[candidate];
    if (value !== undefined && value !== null && value !== '') return value;
  }
  return undefined;
}

function asString(value: unknown): string | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value === 'string') return value.trim() || undefined;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return undefined;
}

function asBoolean(value: unknown): boolean | undefined {
  if (value === undefined || value === null || value === '') return undefined;
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number') return value !== 0;
  if (typeof value === 'string') {
    const v = value.toLowerCase().trim();
    if (['true', '1', 'yes', 'y', 'active', 'enabled'].includes(v)) return true;
    if (['false', '0', 'no', 'n', 'inactive', 'disabled', 'terminated'].includes(v)) return false;
  }
  return undefined;
}

export type NormalizedEmployee = {
  email: string;
  name: string;
  department?: string;
  position?: string;
  phone?: string;
  location?: string;
  employeeType?: 'staff' | 'contractor';
  isActive?: boolean;
  externalId?: string;
};

/**
 * Convert provider records into our employee shape. Records without a usable
 * email are dropped and counted — email is the identity key for the upsert.
 */
export function normalizeEmployees(
  rows: unknown[],
  fieldMapJson?: string,
): { employees: NormalizedEmployee[]; dropped: number } {
  let map: Record<string, string> = {};
  if (fieldMapJson) {
    try {
      const parsed: unknown = JSON.parse(fieldMapJson);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        map = parsed as Record<string, string>;
      }
    } catch {
      throw new Error('Field mapping is not valid JSON');
    }
  }

  const employees: NormalizedEmployee[] = [];
  let dropped = 0;

  for (const row of rows) {
    if (!row || typeof row !== 'object') {
      dropped++;
      continue;
    }
    const record = row as Record<string, unknown>;

    const email = asString(pick(record, 'email', map))?.toLowerCase();
    if (!email || !email.includes('@')) {
      dropped++;
      continue;
    }

    let name = asString(pick(record, 'name', map));
    if (!name) {
      const first = asString(pick(record, 'firstName', map));
      const last = asString(pick(record, 'lastName', map));
      name = [first, last].filter(Boolean).join(' ') || undefined;
    }

    const rawType = asString(pick(record, 'employeeType', map))?.toLowerCase();
    const employeeType =
      rawType === undefined
        ? undefined
        : /contract|freelanc|vendor|temp/.test(rawType)
          ? ('contractor' as const)
          : ('staff' as const);

    employees.push({
      email,
      name: name ?? email,
      department: asString(pick(record, 'department', map)),
      position: asString(pick(record, 'position', map)),
      phone: asString(pick(record, 'phone', map)),
      location: asString(pick(record, 'location', map)),
      employeeType,
      isActive: asBoolean(pick(record, 'isActive', map)),
      externalId: asString(pick(record, 'externalId', map)),
    });
  }

  // Last record wins on duplicate emails, keeping the batch idempotent.
  const byEmail = new Map<string, NormalizedEmployee>();
  for (const e of employees) byEmail.set(e.email, e);

  return { employees: [...byEmail.values()], dropped };
}

// ═══════════════════════════════════════════════════════════════════════════
// HTTP HELPERS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Third-party error bodies can echo back the credentials we sent, and they land
 * in sync logs shown in the UI. Truncate and strip anything secret-looking.
 */
function safeErrorBody(body: string, config: Record<string, unknown>): string {
  let out = body.slice(0, 300);
  for (const field of SECRET_FIELDS) {
    const secret = config?.[field];
    if (typeof secret === 'string' && secret.length >= 6) {
      out = out.split(secret).join(SECRET_MASK);
    }
  }
  if (typeof config?.imidAccessToken === 'string' && config.imidAccessToken.length >= 6) {
    out = out.split(config.imidAccessToken).join(SECRET_MASK);
  }
  return out;
}

/** Join a base URL and path without doubling or dropping the separator. */
function joinUrl(base: string, path: string): string {
  const b = base.replace(/\/+$/, '');
  const p = path.startsWith('/') ? path : `/${path}`;
  return `${b}${p}`;
}

/** Reject non-HTTPS and obviously internal targets — configs are admin-supplied. */
function assertSafeUrl(raw: string, label: string): string {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`${label}: "${raw.slice(0, 60)}" is not a valid URL`);
  }
  if (url.protocol !== 'https:') {
    throw new Error(`${label}: only https:// endpoints are allowed`);
  }
  const host = url.hostname.toLowerCase();
  const isPrivate =
    host === 'localhost' ||
    host === '::1' ||
    host.endsWith('.localhost') ||
    host.endsWith('.internal') ||
    /^127\./.test(host) ||
    /^10\./.test(host) ||
    /^192\.168\./.test(host) ||
    /^169\.254\./.test(host) ||
    /^172\.(1[6-9]|2\d|3[01])\./.test(host);
  if (isPrivate) {
    throw new Error(`${label}: private and loopback hosts are not allowed`);
  }
  return url.toString();
}

/** A provider call that fails or stalls must not hang the whole sync. */
async function fetchJson(
  url: string,
  init: RequestInit,
  label: string,
  config: Record<string, unknown>,
): Promise<unknown> {
  let response: Response;
  try {
    response = await fetch(url, {
      ...init,
      signal: AbortSignal.timeout(20_000),
    });
  } catch (e: unknown) {
    const reason =
      e && typeof e === 'object' && 'name' in e && (e as { name: string }).name === 'TimeoutError'
        ? 'request timed out'
        : 'network error';
    throw new Error(`${label}: ${reason}`);
  }

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`${label} API error (${response.status}): ${safeErrorBody(body, config)}`);
  }

  const text = await response.text();
  if (!text.trim()) {
    throw new Error(`${label}: empty response body`);
  }
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`${label}: response was not JSON — ${safeErrorBody(text, config)}`);
  }
}

/**
 * Call an OAuth 2.0 token endpoint.
 *
 * RFC 6749 §4.1.3 mandates `application/x-www-form-urlencoded` for token
 * requests, so that is what we send first. Some providers only accept JSON,
 * so a 400/415 response — the two statuses a server uses to reject a body it
 * cannot parse — triggers one retry with a JSON body. Any other failure is
 * a genuine error (bad credentials, wrong URL) and propagates immediately.
 */
async function fetchTokenEndpoint(
  url: string,
  params: Record<string, string>,
  label: string,
  config: Record<string, unknown>,
): Promise<Record<string, unknown>> {
  try {
    return (await fetchJson(
      url,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Accept: 'application/json',
        },
        body: new URLSearchParams(params).toString(),
      },
      label,
      config,
    )) as Record<string, unknown>;
  } catch (e: unknown) {
    const message = String(
      e && typeof e === 'object' && 'message' in e ? (e as { message: unknown }).message : '',
    );
    // Only retry when the server rejected the *encoding*, not the credentials.
    if (!/\((400|415)\)/.test(message)) throw e;

    return (await fetchJson(
      url,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify(params),
      },
      label,
      config,
    )) as Record<string, unknown>;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// SYNC ORCHESTRATION
// ═══════════════════════════════════════════════════════════════════════════

type SyncOutcome = {
  message: string;
  created: number;
  updated: number;
  deactivated: number;
  skipped: number;
  details?: string;
  /** True when the provider is connected but importing is switched off. */
  skippedSync?: boolean;
};

async function performSync(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  provider: Provider,
  config: Record<string, unknown>,
): Promise<SyncOutcome> {
  switch (provider) {
    case 'lucky_carrot':
      return syncLuckyCarrot(ctx, organizationId, config);
    case 'imid':
      return syncImid(ctx, organizationId, config);
    case 'armsoft':
      return syncArmsoft(ctx, organizationId, config);
    case 'telegram':
      // Telegram is a config-only integration — no employee sync needed.
      return {
        message: 'Telegram: configuration saved',
        created: 0,
        updated: 0,
        deactivated: 0,
        skipped: 0,
        skippedSync: true,
      };
    default:
      throw new Error(`Unknown provider: ${provider}`);
  }
}

/**
 * Fetch → normalize → upsert, shared by every provider that imports people.
 *
 * Paginated directories are followed page by page (see `findNextPageUrl`) up to
 * the per-run record and page caps, so a provider that returns 100 people at a
 * time still yields a complete import.
 */
async function importEmployees(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  provider: Provider,
  config: Record<string, unknown>,
  url: string,
  headers: Record<string, string>,
  label: string,
): Promise<SyncOutcome> {
  const rows: unknown[] = [];
  const notes: string[] = [];
  let nextUrl: string | undefined = url;
  let pages = 0;
  /** True when a cap stopped us before the provider ran out of pages. */
  let truncated = false;

  while (nextUrl) {
    const payload: unknown = await fetchJson(nextUrl, { method: 'GET', headers }, label, config);
    pages++;

    rows.push(...extractList(payload, config.employeesListKey as string | undefined));
    if (rows.length > MAX_IMPORT_RECORDS) {
      throw new Error(
        `${label}: response contained ${rows.length} records, above the ${MAX_IMPORT_RECORDS} per-run limit. Narrow the query or paginate.`,
      );
    }

    // Only follow a next link that stays on the origin we were pointed at —
    // a provider response must not be able to redirect the sync elsewhere.
    nextUrl = findNextPageUrl(payload, nextUrl);
    if (nextUrl && pages >= MAX_IMPORT_PAGES) {
      truncated = true;
      notes.push(
        `stopped after ${MAX_IMPORT_PAGES} pages — the provider offered more; narrow the query`,
      );
      break;
    }
  }

  const { employees, dropped } = normalizeEmployees(rows, config.fieldMap as string | undefined);
  if (employees.length === 0) {
    throw new Error(
      `${label}: fetched ${rows.length} record(s) but none had a usable email — check the field mapping`,
    );
  }

  let created = 0;
  let updated = 0;
  let skipped = dropped;

  for (let i = 0; i < employees.length; i += UPSERT_BATCH_SIZE) {
    const batch = employees.slice(i, i + UPSERT_BATCH_SIZE);
    const res = await ctx.runMutation(internal.integrations.upsertEmployeeBatch, {
      organizationId,
      provider,
      employees: batch,
    });
    created += res.created;
    updated += res.updated;
    skipped += res.skipped;
    notes.push(...res.notes);
  }

  let deactivated = 0;
  if (config.deactivateMissing) {
    if (truncated) {
      // The list we hold is provably incomplete, and "missing from the list"
      // is exactly the signal this mutation acts on — running it here would
      // deactivate people the provider never got a chance to mention.
      notes.push('deactivation skipped — the employee list was truncated');
    } else {
      const res = await ctx.runMutation(internal.integrations.deactivateMissingEmployees, {
        organizationId,
        // Only people the provider says are active should stay active here.
        activeEmails: employees.filter((e) => e.isActive !== false).map((e) => e.email),
      });
      deactivated = res.deactivated;
    }
  }

  const message = `${label}: ${created} created, ${updated} updated, ${deactivated} deactivated, ${skipped} skipped`;
  return {
    message,
    created,
    updated,
    deactivated,
    skipped,
    details: notes.length ? JSON.stringify(notes.slice(0, 50)) : undefined,
  };
}

// ── Lucky Carrot Sync ──────────────────────────────────────────────────────
async function syncLuckyCarrot(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  config: Record<string, unknown>,
): Promise<SyncOutcome> {
  if (!config.apiKey || !config.apiUrl) {
    throw new Error('Lucky Carrot: API key and URL required');
  }
  if (config.autoSyncEmployees === false) {
    return {
      message: 'Lucky Carrot: credentials verified, employee import is switched off',
      created: 0,
      updated: 0,
      deactivated: 0,
      skipped: 0,
      skippedSync: true,
    };
  }

  const base = assertSafeUrl(config.apiUrl as string, 'Lucky Carrot API URL');
  const url = assertSafeUrl(
    joinUrl(base, (config.employeesPath as string) || '/api/v1/employees'),
    'Lucky Carrot employees URL',
  );

  return importEmployees(
    ctx,
    organizationId,
    'lucky_carrot',
    config,
    url,
    {
      Authorization: `Bearer ${config.apiKey as string}`,
      Accept: 'application/json',
    },
    'Lucky Carrot',
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// LUCKY CARROT INBOUND WEBHOOK
// ═══════════════════════════════════════════════════════════════════════════

/** Header carrying the hex HMAC-SHA256 of `<timestamp>.<body>`. */
export const WEBHOOK_SIGNATURE_HEADER = 'x-luckycarrot-signature';
/** Header carrying the unix-seconds timestamp that is signed alongside the body. */
export const WEBHOOK_TIMESTAMP_HEADER = 'x-luckycarrot-timestamp';

/** Deliveries older than this are rejected, so a captured request cannot be replayed. */
const WEBHOOK_MAX_SKEW_MS = 5 * 60 * 1000;

/** Refuse oversized bodies before spending CPU on HMAC or JSON parsing. */
export const WEBHOOK_MAX_BODY_BYTES = 1_000_000;

/** Outcome of an inbound delivery; the HTTP layer maps this to a status code. */
type WebhookOutcome =
  | { status: 'unauthorized' }
  | { status: 'disabled' }
  | { status: 'invalid'; message: string }
  | { status: 'ok'; message: string; created: number; updated: number; skipped: number };

/**
 * Compare two hex digests without leaking where they diverge. A `===` here would
 * finish early on the first differing character, which is a timing oracle an
 * attacker can walk one nibble at a time to forge a signature.
 */
function timingSafeEqualHex(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

function toHex(buffer: ArrayBuffer): string {
  return Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/** HMAC-SHA256 over `<timestamp>.<body>`, hex-encoded. */
async function signWebhookPayload(
  secret: string,
  timestamp: string,
  body: string,
): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const mac = await crypto.subtle.sign(
    'HMAC',
    key,
    new TextEncoder().encode(`${timestamp}.${body}`),
  );
  return toHex(mac);
}

/** Internal: normalize an organization id from a raw string (for use in actions). */
export const normalizeOrganizationId = internalQuery({
  args: { organizationIdRaw: v.string() },
  handler: async (ctx, { organizationIdRaw }) => {
    return ctx.db.normalizeId('organizations', organizationIdRaw);
  },
});

export const verifyImidWebhookSignature = internalQuery({
  args: {
    organizationIdRaw: v.string(),
    body: v.string(),
    signature: v.string(),
  },
  handler: async (ctx, { organizationIdRaw, body, signature }) => {
    const organizationId = ctx.db.normalizeId('organizations', organizationIdRaw);
    if (!organizationId) return false;
    const doc = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'imid'),
      )
      .first();
    const secret = (doc?.config as Record<string, unknown> | undefined)?.webhookSecret as
      | string
      | undefined;
    if (!secret) return false;
    const { verifyPaymentSignature } = await import('./lib/paymentSignature');
    return verifyPaymentSignature(secret, body, signature);
  },
});

export const hasImidWebhookSecret = internalQuery({
  args: { organizationIdRaw: v.string() },
  handler: async (ctx, { organizationIdRaw }) => {
    const organizationId = ctx.db.normalizeId('organizations', organizationIdRaw);
    if (!organizationId) return false;
    const doc = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'imid'),
      )
      .first();
    const secret = (doc?.config as Record<string, unknown> | undefined)?.webhookSecret as
      | string
      | undefined;
    return Boolean(secret);
  },
});

/**
 * A webhook may carry a whole directory or a single employee event. `extractList`
 * covers the collection shapes; fall back to the common single-record envelopes
 * so a "employee.updated" push does not need a separate code path.
 */
function extractWebhookRecords(payload: unknown, listKey?: string): unknown[] {
  try {
    return extractList(payload, listKey);
  } catch (listError) {
    if (payload && typeof payload === 'object') {
      const envelope = payload as Record<string, unknown>;
      for (const key of ['employee', 'user', 'data', 'record', 'object']) {
        const candidate = envelope[key];
        if (candidate && typeof candidate === 'object' && !Array.isArray(candidate)) {
          return [candidate];
        }
      }
      // A bare employee object posted at the top level.
      if (!Array.isArray(payload)) return [payload];
    }
    throw listError;
  }
}

/**
 * Credentials needed to authenticate an inbound delivery. Takes the org id as a
 * raw string because it arrives from the URL — `normalizeId` both validates it
 * and rejects ids belonging to another table.
 */
export const getWebhookAuth = internalQuery({
  args: { organizationIdRaw: v.string() },
  handler: async (ctx, { organizationIdRaw }) => {
    const organizationId = ctx.db.normalizeId('organizations', organizationIdRaw);
    if (!organizationId) return null;

    const doc = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'lucky_carrot'),
      )
      .first();
    if (!doc?.config.webhookSecret) return null;

    return {
      organizationId,
      secret: doc.config.webhookSecret,
      // Enablement is reported rather than enforced here: the caller checks the
      // signature first, so a legitimate sender gets a clear "disabled" answer
      // while an unauthenticated one learns nothing.
      isEnabled: doc.config.isEnabled === true && doc.config.webhookEnabled === true,
      employeesListKey: doc.config.employeesListKey,
      fieldMap: doc.config.fieldMap,
    };
  },
});

/** Record that a delivery landed, so the UI can show webhook freshness. */
export const markWebhookReceived = internalMutation({
  args: { organizationId: v.id('organizations') },
  handler: async (ctx, { organizationId }) => {
    const existing = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'lucky_carrot'),
      )
      .first();
    if (!existing) return;

    await ctx.db.patch(existing._id, {
      config: { ...existing.config, lastWebhookAt: Date.now() },
      updatedAt: Date.now(),
    });
  },
});

/**
 * Authenticate and apply one inbound Lucky Carrot delivery.
 *
 * Kept out of the HTTP handler so the signing secret never enters the routing
 * layer, and so the whole path is unit-testable without a live request.
 *
 * Unlike a scheduled sync this never deactivates anyone: a webhook payload is
 * usually a single event or a partial page, and treating "absent from this push"
 * as "no longer employed" would lock out the whole organization.
 */
export const ingestLuckyCarrotWebhook = internalAction({
  args: {
    organizationIdRaw: v.string(),
    body: v.string(),
    signature: v.string(),
    timestamp: v.string(),
  },
  handler: async (ctx, args): Promise<WebhookOutcome> => {
    const { organizationIdRaw, body, signature, timestamp } = args;

    if (!signature || !timestamp) return { status: 'unauthorized' };

    const auth: {
      organizationId: Id<'organizations'>;
      secret: string;
      isEnabled: boolean;
      employeesListKey?: string;
      fieldMap?: string;
    } | null = await ctx.runQuery(internal.integrations.getWebhookAuth, { organizationIdRaw });
    // An unknown org, an unconfigured provider and a bad signature are all
    // reported identically — otherwise this endpoint enumerates organizations.
    if (!auth) return { status: 'unauthorized' };

    const sentAt = Number(timestamp);
    if (!Number.isFinite(sentAt)) return { status: 'unauthorized' };
    // Seconds and milliseconds are both accepted; senders differ.
    const sentAtMs = sentAt > 1e11 ? sentAt : sentAt * 1000;
    if (Math.abs(Date.now() - sentAtMs) > WEBHOOK_MAX_SKEW_MS) {
      return { status: 'unauthorized' };
    }

    const expected = await signWebhookPayload(auth.secret, timestamp, body);
    if (!timingSafeEqualHex(signature.trim().toLowerCase(), expected)) {
      return { status: 'unauthorized' };
    }

    // Past this line the sender is proven authentic, so it is safe to give it
    // specific feedback — and to write to the sync log without letting an
    // anonymous caller flood the table.
    if (!auth.isEnabled) return { status: 'disabled' };

    let payload: unknown;
    try {
      payload = JSON.parse(body);
    } catch {
      return { status: 'invalid', message: 'Body was not valid JSON' };
    }

    let records: unknown[];
    try {
      records = extractWebhookRecords(payload, auth.employeesListKey);
    } catch (error: unknown) {
      return {
        status: 'invalid',
        message:
          error && typeof error === 'object' && 'message' in error
            ? String((error as { message: unknown }).message)
            : 'Unrecognized payload shape',
      };
    }

    if (records.length > MAX_IMPORT_RECORDS) {
      return {
        status: 'invalid',
        message: `Delivery contained ${records.length} records, above the ${MAX_IMPORT_RECORDS} per-request limit`,
      };
    }

    let normalized: { employees: NormalizedEmployee[]; dropped: number };
    try {
      normalized = normalizeEmployees(records, auth.fieldMap);
    } catch (error: unknown) {
      return {
        status: 'invalid',
        message:
          error && typeof error === 'object' && 'message' in error
            ? String((error as { message: unknown }).message)
            : 'Could not read the payload',
      };
    }

    const { employees, dropped } = normalized;
    if (employees.length === 0) {
      return {
        status: 'invalid',
        message: `Received ${records.length} record(s) but none had a usable email — check the field mapping`,
      };
    }

    let created = 0;
    let updated = 0;
    let skipped = dropped;
    const notes: string[] = [];

    for (let i = 0; i < employees.length; i += UPSERT_BATCH_SIZE) {
      const res = await ctx.runMutation(internal.integrations.upsertEmployeeBatch, {
        organizationId: auth.organizationId,
        provider: 'lucky_carrot' as const,
        employees: employees.slice(i, i + UPSERT_BATCH_SIZE),
      });
      created += res.created;
      updated += res.updated;
      skipped += res.skipped;
      notes.push(...res.notes);
    }

    const message = `Lucky Carrot webhook: ${created} created, ${updated} updated, ${skipped} skipped`;

    await ctx.runMutation(internal.integrations.logSync, {
      organizationId: auth.organizationId,
      provider: 'lucky_carrot' as const,
      action: 'webhook',
      status: 'success',
      message,
      created,
      updated,
      deactivated: 0,
      skipped,
      details: notes.length ? JSON.stringify(notes.slice(0, 50)) : undefined,
    });

    await ctx.runMutation(internal.integrations.markWebhookReceived, {
      organizationId: auth.organizationId,
    });

    return { status: 'ok', message, created, updated, skipped };
  },
});

/**
 * Mint a new webhook signing secret and return it once.
 *
 * Rotating invalidates the previous secret immediately, so the value must be
 * copied into Lucky Carrot before the next delivery. It is deliberately absent
 * from every read path (see SERVER_ONLY_FIELDS) — this mutation's return value
 * is the only time it is ever transmitted.
 */
export const rotateWebhookSecret = mutation({
  args: { organizationId: v.id('organizations') },
  handler: async (ctx, { organizationId }) => {
    await assertModuleAccess(ctx, 'integrations');
    const caller = await getAuthCaller(ctx);
    if (!caller) throw new Error('Not authenticated');
    if (!canAdminOrg(caller, organizationId)) {
      throw new Error('Only admins of this organization can manage webhooks');
    }

    const existing = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'lucky_carrot'),
      )
      .first();
    if (!existing) {
      throw new Error('Save the Lucky Carrot configuration before generating a webhook secret');
    }

    // 256 bits of entropy, hex-encoded — the same shape the HMAC key expects.
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    const secret = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');

    const now = Date.now();
    await ctx.db.patch(existing._id, {
      config: { ...existing.config, webhookSecret: secret },
      updatedAt: now,
    });

    await ctx.db.insert('auditLogs', {
      organizationId,
      userId: caller._id,
      action: 'integration_lucky_carrot_webhook_secret_rotated',
      target: 'lucky_carrot',
      details: JSON.stringify({ rotated: true }),
      createdAt: now,
    });

    return { secret };
  },
});

// ── imID Sync ──────────────────────────────────────────────────────────────
/**
 * imID is an identity provider, not an HR system: there is no employee
 * directory to pull. A sync therefore validates the OAuth client-credentials
 * grant and caches the resulting token for signing/verification calls.
 */
async function syncImid(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  config: Record<string, unknown>,
): Promise<SyncOutcome> {
  if (!config.clientId || !config.clientSecret) {
    throw new Error('imID: Client ID and Client Secret required');
  }
  if ((config.enableLogin as boolean) && !config.redirectUri) {
    throw new Error('imID: Redirect URI is required when login with imID is enabled');
  }
  if (config.redirectUri) {
    assertSafeUrl(config.redirectUri as string, 'imID Redirect URI');
  }

  const tokenUrl = assertSafeUrl(
    (config.tokenPath as string) || 'https://api.imid.am/v1/oauth/token',
    'imID token URL',
  );

  const payload = await fetchTokenEndpoint(
    tokenUrl,
    {
      client_id: config.clientId as string,
      client_secret: config.clientSecret as string,
      grant_type: 'client_credentials',
    },
    'imID auth',
    config,
  );

  const accessToken =
    asString(payload.access_token) ?? asString(payload.accessToken) ?? asString(payload.token);
  if (!accessToken) {
    throw new Error('imID: auth succeeded but no access_token was returned');
  }

  const expiresInRaw = payload.expires_in ?? payload.expiresIn;
  const expiresIn = typeof expiresInRaw === 'number' ? expiresInRaw : 3600;
  // Expire a minute early so a token is never used on the edge of validity.
  const expiresAt = Date.now() + Math.max(60, expiresIn - 60) * 1000;

  await ctx.runMutation(internal.integrations.cacheImidToken, {
    organizationId,
    accessToken,
    expiresAt,
  });

  const enabled = [
    config.enableLogin ? 'login' : null,
    config.enableSigning ? 'e-signature' : null,
    config.enableVerification ? 'verification' : null,
  ].filter(Boolean);

  return {
    message: `imID: authenticated, token cached until ${new Date(expiresAt).toISOString()}${
      enabled.length ? ` (enabled: ${enabled.join(', ')})` : ' (no features enabled yet)'
    }`,
    created: 0,
    updated: 0,
    deactivated: 0,
    skipped: 0,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// imID OAUTH LOGIN FLOW
// ═══════════════════════════════════════════════════════════════════════════

/** Default imID OAuth endpoints — used when no path override is saved. */
const IMID_AUTHORIZE_DEFAULT = 'https://api.imid.am/v1/oauth/authorize';
const IMID_USERINFO_DEFAULT = 'https://api.imid.am/v1/oauth/userinfo';
const IMID_SIGNING_DEFAULT = 'https://api.imid.am/v1/sign';

/** Result of an imID employee verification request. */
type ImidVerifyResult =
  | { verified: boolean; method: 'sub' }
  | { verified: false; method: 'phone'; requestId?: string; message: string };

/** Result of an imID login callback; returned via the HTTP handler redirect. */
type ImidLoginResult =
  | { status: 'error'; message: string }
  | {
      status: 'ok';
      sessionToken: string;
      sessionExpiry: number;
      userId: Id<'users'>;
      isNewUser: boolean;
      needsApproval: boolean;
    };

/**
 * Generate the authorize URL for the imID OAuth login flow.
 *
 * The frontend calls this query, then redirects the browser to the returned URL.
 * After authentication, imID redirects to the callback endpoint with an
 * authorization code that `imidLoginCallback` exchanges for a session.
 */
export const imidGetAuthorizationUrl = mutation({
  args: { organizationId: v.id('organizations') },
  handler: async (ctx, { organizationId }) => {
    // Public mutation — called from the login page before the user is authenticated.
    // Must be a mutation because it writes the OAuth state to the config.
    // CSRF protection is provided by the OAuth state parameter.
    const config = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_org_provider', (q) =>
        q.eq('organizationId', organizationId).eq('provider', 'imid'),
      )
      .first();

    if (!config || !config.config.isEnabled || !config.config.enableLogin) {
      throw new Error('imID login is not enabled for this organization');
    }
    if (!config.config.clientId || !config.config.redirectUri) {
      throw new Error('imID: Client ID and Redirect URI must be configured');
    }

    const authorizeUrl = assertSafeUrl(
      config.config.authorizePath || IMID_AUTHORIZE_DEFAULT,
      'imID authorize URL',
    );

    // Generate a secure random state parameter to prevent CSRF.
    const stateBytes = new Uint8Array(32);
    crypto.getRandomValues(stateBytes);
    const state = Array.from(stateBytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');

    // Persist the state so the callback can validate it.
    await ctx.db.patch(config._id, {
      config: { ...config.config, oauthState: state },
    });

    const params = new URLSearchParams({
      client_id: config.config.clientId,
      redirect_uri: config.config.redirectUri,
      response_type: 'code',
      scope: 'openid profile email',
      state,
    });

    return { url: `${authorizeUrl}?${params.toString()}`, state };
  },
});

/**
 * Exchange an OAuth authorization code for an access token from imID.
 * Used by `imidLoginCallback` to complete the OAuth flow.
 */
export const imidExchangeCode = internalAction({
  args: {
    organizationId: v.id('organizations'),
    code: v.string(),
    redirectUri: v.string(),
  },
  handler: async (ctx, { organizationId, code, redirectUri }) => {
    const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
      organizationId,
      provider: 'imid',
    });
    if (!config) throw new Error('imID config not found');

    const tokenUrl = assertSafeUrl(
      config.config.tokenPath || 'https://api.imid.am/v1/oauth/token',
      'imID token URL',
    );

    const { clientId, clientSecret } = config.config;
    if (!clientId || !clientSecret) {
      throw new Error('imID: Client ID and Client Secret must be configured');
    }

    const payload = await fetchTokenEndpoint(
      tokenUrl,
      {
        client_id: clientId,
        client_secret: clientSecret,
        grant_type: 'authorization_code',
        code,
        redirect_uri: redirectUri,
      },
      'imID token exchange',
      config.config,
    );

    const accessToken =
      asString(payload.access_token) ?? asString(payload.accessToken) ?? asString(payload.token);
    if (!accessToken) {
      throw new Error('imID: token exchange succeeded but no access_token was returned');
    }

    const idToken = asString(payload.id_token);

    return { accessToken, idToken, raw: payload };
  },
});

/**
 * Fetch user info from the imID userinfo endpoint using the access token.
 * Returns the user's email, name, and any other available claims.
 */
export const imidGetUserInfo = internalAction({
  args: {
    organizationId: v.id('organizations'),
    accessToken: v.string(),
  },
  handler: async (ctx, { organizationId, accessToken }) => {
    const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
      organizationId,
      provider: 'imid',
    });
    if (!config) throw new Error('imID config not found');

    const userInfoUrl = assertSafeUrl(
      config.config.userInfoPath || IMID_USERINFO_DEFAULT,
      'imID userinfo URL',
    );

    const payload = (await fetchJson(
      userInfoUrl,
      {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: 'application/json',
        },
      },
      'imID userinfo',
      config.config,
    )) as Record<string, unknown>;

    const email =
      asString(payload.email) ??
      asString(payload.preferred_username) ??
      asString(payload.sub) ??
      '';
    const nameRaw = asString(payload.name);
    const given = asString(payload.given_name);
    const family = asString(payload.family_name);
    const name = nameRaw || [given, family].filter(Boolean).join(' ') || 'User';
    const sub = asString(payload.sub) ?? email;
    const phone = asString(payload.phone_number) ?? asString(payload.phone);

    if (!email) {
      throw new Error('imID: userinfo did not return an email');
    }

    return {
      sub,
      email: email.toLowerCase(),
      name,
      phone,
      raw: payload,
    };
  },
});

/**
 * Clear the one-time OAuth state from the imID integration config.
 * Extracted into a mutation because `imidLoginCallback` is an internal action
 * and has no direct `ctx.db`.
 */
export const clearImidOauthState = internalMutation({
  args: { configId: v.id('integrationConfigs') },
  handler: async (ctx, { configId }) => {
    const doc = await ctx.db.get(configId);
    if (!doc) return;
    const cleaned: Record<string, unknown> = { ...doc.config };
    delete cleaned.oauthState;
    await ctx.db.patch(configId, { config: cleaned as Doc<'integrationConfigs'>['config'] });
  },
});

/**
 * Full OAuth login callback — exchange code, fetch user, create/login.
 * Called from the HTTP handler after imID redirects the user back.
 *
 * Returns a signed session token the HTTP handler bakes into the redirect
 * cookie, so the user lands in the app already authenticated.
 */
export const imidLoginCallback = internalAction({
  args: {
    organizationId: v.id('organizations'),
    code: v.string(),
    state: v.string(),
  },
  // Annotated explicitly: the handler calls ctx.runAction through
  // internal.integrations which creates a circular reference — without the
  // annotation TS cannot break the inference cycle.
  handler: async (ctx, { organizationId, code, state }): Promise<ImidLoginResult> => {
    const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
      organizationId,
      provider: 'imid',
    });
    if (!config) {
      return { status: 'error', message: 'imID configuration not found' } as const;
    }

    // Validate state (CSRF protection).
    if (config.config.oauthState && config.config.oauthState !== state) {
      return {
        status: 'error',
        message: 'Invalid state parameter — possible CSRF attack',
      } as const;
    }

    // Clear the state regardless of outcome (one-time use).
    await ctx.runMutation(internal.integrations.clearImidOauthState, { configId: config._id });

    const redirectUri = config.config.redirectUri || '';
    if (!redirectUri) {
      return { status: 'error', message: 'Redirect URI not configured' } as const;
    }

    // Exchange the authorization code for an access token.
    let tokenResult: { accessToken: string; idToken?: string | null };
    try {
      tokenResult = await ctx.runAction(internal.integrations.imidExchangeCode, {
        organizationId,
        code,
        redirectUri,
      });
    } catch (error: unknown) {
      return {
        status: 'error',
        message:
          error && typeof error === 'object' && 'message' in error
            ? String((error as { message: unknown }).message)
            : 'Token exchange failed',
      } as const;
    }

    // Fetch user info from imID.
    let userInfo: { sub: string; email: string; name: string; phone?: string };
    try {
      userInfo = await ctx.runAction(internal.integrations.imidGetUserInfo, {
        organizationId,
        accessToken: tokenResult.accessToken,
      });
    } catch (error: unknown) {
      return {
        status: 'error',
        message:
          error && typeof error === 'object' && 'message' in error
            ? String((error as { message: unknown }).message)
            : 'Failed to fetch user info',
      } as const;
    }

    // Create or log in the user via the auth module.
    try {
      const sessionToken = crypto.randomUUID();
      const sessionExpiry = Date.now() + 7 * 24 * 60 * 60 * 1000; // 7 days

      const result = await ctx.runMutation(internal.integrations.imidUpsertUser, {
        organizationId,
        email: userInfo.email,
        name: userInfo.name,
        phone: userInfo.phone,
        imidSub: userInfo.sub,
        sessionToken,
        sessionExpiry,
      });

      return {
        status: 'ok',
        sessionToken,
        sessionExpiry,
        userId: result.userId,
        isNewUser: result.isNewUser,
        needsApproval: result.needsApproval,
      } as const;
    } catch (error: unknown) {
      return {
        status: 'error',
        message:
          error && typeof error === 'object' && 'message' in error
            ? String((error as { message: unknown }).message)
            : 'Failed to create session',
      } as const;
    }
  },
});

/**
 * Upsert a user logging in via imID OAuth.
 *
 * If the user's email exists in this org → log them in.
 * If not → create a new user (pending approval unless first in org).
 */
export const imidUpsertUser = internalMutation({
  args: {
    organizationId: v.id('organizations'),
    email: v.string(),
    name: v.string(),
    phone: v.optional(v.string()),
    imidSub: v.string(),
    sessionToken: v.string(),
    sessionExpiry: v.number(),
  },
  handler: async (ctx, args) => {
    const { organizationId, email, name, phone, imidSub, sessionToken, sessionExpiry } = args;
    const normalizedEmail = email.toLowerCase().trim();

    // Look up the user by email within this org.
    const existing = await ctx.db
      .query('users')
      .withIndex('by_org_email', (q) =>
        q.eq('organizationId', organizationId).eq('email', normalizedEmail),
      )
      .first();

    if (existing) {
      if (!existing.isActive) {
        throw new Error('Your account has been deactivated. Contact your administrator.');
      }
      if (!existing.isApproved) {
        throw new Error('Your account is pending approval.');
      }

      // Update session and imID subject id.
      await ctx.db.patch(existing._id, {
        sessionToken,
        sessionExpiry,
        lastLoginAt: Date.now(),
        imidSub,
      });

      return { userId: existing._id, isNewUser: false, needsApproval: false };
    }

    // New user — check org limits and create.
    const org = await ctx.db.get(organizationId);
    if (!org || !org.isActive) throw new Error('Organization is inactive');

    const activeUsersRaw2 = await ctx.db
      .query('users')
      .withIndex('by_org_active', (q) =>
        q.eq('organizationId', organizationId).eq('isActive', true),
      )
      .take(DEFAULT_LIST_CAP + 1);
    const isCappedActiveUsers2 = activeUsersRaw2.length > DEFAULT_LIST_CAP;
    void isCappedActiveUsers2;
    const activeUsers = activeUsersRaw2.slice(0, DEFAULT_LIST_CAP);

    if (activeUsers.length >= org.employeeLimit) {
      throw new Error('Organization has reached its employee limit');
    }

    const isFirstMember = activeUsers.length === 0;
    const role = isFirstMember ? 'admin' : 'employee';
    const isApproved = isFirstMember;

    const userId = await ctx.db.insert('users', {
      organizationId,
      name: name || normalizedEmail.split('@')[0] || 'User',
      email: normalizedEmail,
      passwordHash: '', // OAuth-only user
      phone,
      role,
      employeeType: 'staff',
      isActive: true,
      isApproved,
      approvedAt: isApproved ? Date.now() : undefined,
      imidSub,
      sessionToken: isApproved ? sessionToken : undefined,
      sessionExpiry: isApproved ? sessionExpiry : undefined,
      lastLoginAt: isApproved ? Date.now() : undefined,
      travelAllowance: await resolveTravelAllowanceForOrg(ctx, organizationId, 'staff'),
      ...(await getStartingLeaveBalances(ctx, organizationId)),
      createdAt: Date.now(),
    });

    if (!isApproved) {
      // Notify admins.
      const admins = await ctx.db
        .query('users')
        .withIndex('by_org_role', (q) => q.eq('organizationId', organizationId).eq('role', 'admin'))
        .take(20);

      for (const admin of admins) {
        await notify(ctx, {
          organizationId,
          userId: admin._id,
          type: 'join_request',
          titleKey: 'notifications.titles.imidSignUp',
          messageKey: 'notifications.messages.imidSignUp',
          params: {
            name,
            email: normalizedEmail,
            orgName: org.name || 'organization',
          },
          fallbackTitle: '🙋 New imID Sign-Up',
          fallbackMessage: `${name} (${normalizedEmail}) signed up with imID and wants to join ${org.name || 'organization'}.`,
          relatedId: userId,
          route: '/join-requests',
        });
      }
    }

    return { userId, isNewUser: true, needsApproval: !isApproved };
  },
});

// ═══════════════════════════════════════════════════════════════════════════
// imID SIGN — e-signature via imID Sign API
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Initiate a signing request via the imID Sign API.
 *
 * Uses the cached access token from `syncImid` to authenticate.
 * If the token has expired, the caller should re-sync first.
 *
 * @param documentId — the internal signature document to be signed.
 * @param signerPhone — the phone number of the person who should sign.
 * @param documentTitle — a human-readable title shown in the imID app.
 * @param documentContent — the content/PDF to be signed (base64 or text).
 */
export const imidInitiateSigning = action({
  args: {
    organizationId: v.id('organizations'),
    documentId: v.id('signatureDocuments'),
    signerPhone: v.string(),
    documentTitle: v.string(),
    documentContent: v.string(),
    callbackUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const caller = await ctx.runQuery(internal.integrations.assertCanSync, {
      organizationId: args.organizationId,
    });
    if (!caller) throw new Error('Not authorized');

    const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
      organizationId: args.organizationId,
      provider: 'imid',
    });
    if (!config || !config.config.isEnabled || !config.config.enableSigning) {
      throw new Error('imID Sign is not enabled for this organization');
    }

    const accessToken = config.config.imidAccessToken;
    if (!accessToken) {
      throw new Error('imID: no cached access token — run Sync first');
    }
    if (config.config.imidTokenExpiresAt && config.config.imidTokenExpiresAt < Date.now()) {
      throw new Error('imID: cached token has expired — run Sync to refresh');
    }

    const signingUrl = assertSafeUrl(
      config.config.signingPath || IMID_SIGNING_DEFAULT,
      'imID Sign URL',
    );

    const body = {
      phone: args.signerPhone,
      title: args.documentTitle,
      content: args.documentContent,
      callback_url: args.callbackUrl || `${process.env.CONVEX_SITE_URL || ''}/webhooks/imid/sign`,
      document_id: args.documentId,
    };

    const payload = (await fetchJson(
      signingUrl,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify(body),
      },
      'imID Sign',
      config.config,
    )) as Record<string, unknown>;

    const signingId =
      asString(payload.signing_id) ?? asString(payload.id) ?? asString(payload.request_id);

    await ctx.runMutation(internal.integrations.logSync, {
      organizationId: args.organizationId,
      provider: 'imid',
      action: 'sign_initiated',
      status: 'success',
      message: `imID Sign initiated for ${args.signerPhone}: ${args.documentTitle}`,
    });

    return {
      success: true,
      signingId,
      message: `Signing request sent to ${args.signerPhone}`,
    };
  },
});

/**
 * Webhook handler for imID Sign callbacks.
 * Called by imID when a user has completed or declined a signing request.
 */
export const ingestImidSignCallback = internalAction({
  args: {
    organizationIdRaw: v.string(),
    body: v.string(),
  },
  handler: async (ctx, { organizationIdRaw, body }) => {
    const organizationId = await ctx.runQuery(internal.integrations.normalizeOrganizationId, {
      organizationIdRaw,
    });
    if (!organizationId) {
      return { status: 'invalid', message: 'Unknown organization' } as const;
    }

    let payload: Record<string, unknown>;
    try {
      payload = JSON.parse(body) as Record<string, unknown>;
    } catch {
      return { status: 'invalid', message: 'Body was not valid JSON' } as const;
    }

    const signingStatus = asString(payload.status) ?? asString(payload.event) ?? '';
    const documentId = asString(payload.document_id) ?? asString(payload.documentId) ?? '';

    if (signingStatus === 'completed' || signingStatus === 'signed') {
      // Mark the internal signature request as completed.
      if (documentId && documentId.startsWith('signature')) {
        try {
          await ctx.runMutation(internal.integrations.markImidSignComplete, {
            documentId: documentId as Id<'signatureDocuments'>,
          });
        } catch {
          // Document may not exist — log and continue.
        }
      }

      await ctx.runMutation(internal.integrations.logSync, {
        organizationId,
        provider: 'imid',
        action: 'sign_completed',
        status: 'success',
        message: `imID Sign completed for document ${documentId}`,
      });

      return { status: 'ok', message: 'Signing completed' } as const;
    }

    if (signingStatus === 'declined' || signingStatus === 'rejected') {
      await ctx.runMutation(internal.integrations.logSync, {
        organizationId,
        provider: 'imid',
        action: 'sign_declined',
        status: 'success',
        message: `imID Sign declined for document ${documentId}`,
      });

      return { status: 'ok', message: 'Signing declined' } as const;
    }

    return { status: 'ok', message: 'Unrecognized status, acknowledged' } as const;
  },
});

/** Mark an internal signature request as completed by imID Sign webhook. */
export const markImidSignComplete = internalMutation({
  args: { documentId: v.id('signatureDocuments') },
  handler: async (ctx, { documentId }) => {
    const doc = await ctx.db.get(documentId);
    if (!doc || doc.status === 'completed') return;

    const now = Date.now();

    // Close the outstanding signature requests too. Previously only the document
    // was flipped to `completed`, so every UI surface kept showing "awaiting
    // signature", and the bookkeeping that hangs off a signed request (hiring
    // packet progress, PDF archiving) never ran.
    //
    // No `signatureData` is written on purpose: imID produces a qualified
    // cryptographic signature, not a drawn image. The rendered document shows the
    // signer's name and date over the signature line, and the imID provenance is
    // recorded in `consentText` plus the audit log.
    const requests = await ctx.db
      .query('signatureRequests')
      .withIndex('by_document', (q) => q.eq('documentId', documentId))
      .take(100);

    for (const request of requests) {
      if (request.status !== 'pending') continue;
      await ctx.db.patch(request._id, {
        status: 'signed',
        signedAt: now,
        consentText: `${request.signerName} signed this document electronically via imID.`,
      });
    }

    await ctx.db.patch(documentId, {
      status: 'completed',
      completedAt: now,
    });

    // Keep hiring packet progress in step — the same sync in-app signing does.
    const packetDoc = await ctx.db
      .query('hiringPacketDocuments')
      .withIndex('by_signature_document', (q) => q.eq('signatureDocumentId', documentId))
      .first();
    if (packetDoc && packetDoc.status !== 'signed') {
      await ctx.db.patch(packetDoc._id, {
        status: 'signed',
        signedAt: now,
        updatedAt: now,
      });
    }

    await ctx.db.insert('signatureAuditLog', {
      documentId,
      organizationId: doc.organizationId,
      userId: doc.createdBy,
      action: 'signed',
      metadata: JSON.stringify({ source: 'imid_sign', timestamp: now }),
      timestamp: now,
    });
  },
});

// ═══════════════════════════════════════════════════════════════════════════
// imID VERIFICATION — employee identity verification
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Verify an employee's identity through imID.
 *
 * Uses the cached access token and expects the user's imID subject ID (sub)
 * to have been stored on the user record during OAuth login. If the user has
 * never logged in via imID, a phone-based verification can be used instead.
 */
export const imidVerifyEmployee = action({
  args: {
    organizationId: v.id('organizations'),
    userId: v.id('users'),
    /** Used when the user has no imID sub — send verification to their phone. */
    phone: v.optional(v.string()),
  },
  // Annotated explicitly: the handler reaches into `internal.integrations` for
  // authorization and verification, creating a circular reference that TS
  // cannot break without an explicit return type annotation.
  handler: async (ctx, args): Promise<ImidVerifyResult> => {
    const caller = await ctx.runQuery(internal.integrations.assertCanSync, {
      organizationId: args.organizationId,
    });
    if (!caller) throw new Error('Not authorized');

    const config = await ctx.runQuery(internal.integrations.getIntegrationConfigInternal, {
      organizationId: args.organizationId,
      provider: 'imid',
    });
    if (!config || !config.config.isEnabled || !config.config.enableVerification) {
      throw new Error('imID Verification is not enabled for this organization');
    }

    const accessToken = config.config.imidAccessToken;
    if (!accessToken) {
      throw new Error('imID: no cached access token — run Sync first');
    }
    if (config.config.imidTokenExpiresAt && config.config.imidTokenExpiresAt < Date.now()) {
      throw new Error('imID: cached token has expired — run Sync to refresh');
    }

    const user = await ctx.runQuery(internal.integrations.getUserForVerification, {
      userId: args.userId,
    });
    if (!user) throw new Error('User not found');

    // Try subject-based verification first (user logged in via imID before).
    if (user.imidSub) {
      const verifyUrl = assertSafeUrl(
        config.config.userInfoPath || IMID_USERINFO_DEFAULT,
        'imID verify URL',
      );

      const payload = (await fetchJson(
        verifyUrl,
        {
          method: 'GET',
          headers: {
            Authorization: `Bearer ${accessToken}`,
            Accept: 'application/json',
          },
        },
        'imID verification',
        config.config,
      )) as Record<string, unknown>;

      const verified =
        asString(payload.sub) === user.imidSub ||
        asString(payload.email)?.toLowerCase() === user.email.toLowerCase();

      await ctx.runMutation(internal.integrations.logSync, {
        organizationId: args.organizationId,
        provider: 'imid',
        action: 'verification',
        status: verified ? 'success' : 'error',
        message: verified
          ? `Verified ${user.name} (${user.email}) via imID`
          : `Verification failed for ${user.email}`,
      });

      return { verified, method: 'sub' };
    }

    // Fallback: phone-based verification request.
    if (args.phone) {
      const verifyUrl = assertSafeUrl(
        config.config.signingPath || IMID_SIGNING_DEFAULT,
        'imID verify URL',
      );

      const payload = (await fetchJson(
        `${verifyUrl}/verify`,
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': 'application/json',
            Accept: 'application/json',
          },
          body: JSON.stringify({
            phone: args.phone,
            purpose: 'employee_verification',
            callback_url: `${process.env.CONVEX_SITE_URL || ''}/webhooks/imid/verify`,
          }),
        },
        'imID phone verification',
        config.config,
      )) as Record<string, unknown>;

      const requestId = asString(payload.request_id) ?? asString(payload.id);

      return {
        verified: false,
        method: 'phone',
        requestId,
        message: `Verification request sent to ${args.phone}`,
      };
    }

    throw new Error('imID: cannot verify — user has no imID subject and no phone was provided');
  },
});

/**
 * Resolve an organization id from an OAuth state parameter.
 *
 * Scans all imID integration configs for a matching `oauthState`.
 * This is an action instead of a query because httpActions cannot call queries
 * with arbitrary args — but they can call actions. The action delegates to an
 * internal query internally.
 */
export const imidResolveOrgByState = internalAction({
  args: { state: v.string() },
  // Annotated explicitly: the handler queries internal.integrations which
  // creates a circular reference — without the annotation TS cannot break
  // the inference cycle.
  handler: async (ctx, { state }): Promise<{ organizationId: Id<'organizations'> } | null> => {
    // We need to scan configs, so use the internal list query.
    const configs = await ctx.runQuery(internal.integrations.listAllImidConfigs, {});
    for (const cfg of configs) {
      if (cfg.oauthState === state) {
        return { organizationId: cfg.organizationId };
      }
    }
    return null;
  },
});

/**
 * List organizations that have imID login enabled.
 * Used by the login page to show the "Login with imID" button.
 * Returns org id, name, slug so the frontend can display a picker if needed.
 */
export const imidListEnabledOrgs = query({
  args: {},
  handler: async (ctx) => {
    const docs = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_provider_enabled', (q) =>
        q.eq('provider', 'imid').eq('config.isEnabled', true),
      )
      .take(50);

    const enabled = docs.filter(/* has login enabled */ (d) => d.config.enableLogin === true);
    if (enabled.length === 0) return [];

    // Resolve org names.
    const orgs = await Promise.all(
      enabled.map(async (d) => {
        const org = await ctx.db.get(d.organizationId);
        if (!org || !org.isActive) return null;
        return {
          id: d.organizationId,
          name: org.name,
          slug: org.slug,
          hasLogin: d.config.enableLogin === true,
        };
      }),
    );

    return orgs.filter(Boolean);
  },
});

/**
 * Process an inbound imID verify webhook callback.
 *
 * Called from the HTTP handler because `httpAction` has no direct `ctx.db`.
 * Validates the organization, parses the webhook body, and logs the
 * verification result.
 */
export const ingestImidVerifyCallback = internalAction({
  args: {
    organizationIdRaw: v.string(),
    body: v.string(),
  },
  handler: async (ctx, { organizationIdRaw, body }) => {
    const organizationId = await ctx.runQuery(internal.integrations.normalizeOrganizationId, {
      organizationIdRaw,
    });
    if (!organizationId) {
      return { status: 'invalid', message: 'Unknown organization' } as const;
    }

    let payload: Record<string, unknown>;
    try {
      payload = JSON.parse(body) as Record<string, unknown>;
    } catch {
      return { status: 'invalid', message: 'Body was not valid JSON' } as const;
    }

    const verified = payload.verified === true || payload.status === 'verified';

    if (verified) {
      await ctx.runMutation(internal.integrations.logSync, {
        organizationId,
        provider: 'imid',
        action: 'verification_completed',
        status: 'success',
        message: 'Phone verification completed successfully',
      });
    }

    return { status: 'ok', message: 'Verified' } as const;
  },
});

/** Internal: list all imID configs (for state resolution). */
export const listAllImidConfigs = internalQuery({
  args: {},
  handler: async (ctx) => {
    const docs = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_provider_enabled', (q) => q.eq('provider', 'imid'))
      .take(100);

    return docs.map((d) => ({
      organizationId: d.organizationId,
      oauthState: d.config.oauthState ?? null,
    }));
  },
});

/** Internal: fetch a user with their imID subject for verification. */
export const getUserForVerification = internalQuery({
  args: { userId: v.id('users') },
  handler: async (ctx, { userId }) => {
    const user = await ctx.db.get(userId);
    if (!user) return null;
    // imidSub is defined in the schema — read it from the raw doc shape.
    const userRecord = user as Record<string, unknown>;
    return {
      name: user.name,
      email: user.email,
      imidSub: typeof userRecord.imidSub === 'string' ? userRecord.imidSub : undefined,
    };
  },
});

// ── Armsoft (ՀԾ) Sync ─────────────────────────────────────────────────────
async function syncArmsoft(
  ctx: ActionCtx,
  organizationId: Id<'organizations'>,
  config: Record<string, unknown>,
): Promise<SyncOutcome> {
  if (!config.apiEndpoint) {
    throw new Error('ՀԾ Armsoft: API endpoint required');
  }
  if (!config.apiKey) {
    throw new Error('ՀԾ Armsoft: API key required');
  }
  if (!config.syncEmployees && !config.syncPayroll) {
    return {
      message: 'ՀԾ Armsoft: nothing to sync — enable employee directory or payroll sync',
      created: 0,
      updated: 0,
      deactivated: 0,
      skipped: 0,
      skippedSync: true,
    };
  }

  const base = assertSafeUrl(config.apiEndpoint as string, 'ՀԾ Armsoft API endpoint');
  const headers = {
    apiKey: config.apiKey as string,
    Accept: 'application/json',
    'Accept-Language': 'en-US',
  };

  const notes: string[] = [];

  if (config.syncPayroll) {
    // Payroll import is not implemented. Record that plainly rather than
    // folding it into a "success" the data does not back up.
    notes.push('payroll sync is not implemented yet and was not attempted');
  }

  if (!config.syncEmployees) {
    // Payroll was the only thing switched on, and we cannot do it — so this run
    // imported nothing and must not be logged or displayed as a completed sync.
    return {
      message: ['ՀԾ Armsoft: nothing was synced', ...notes].join('; '),
      created: 0,
      updated: 0,
      deactivated: 0,
      skipped: 0,
      skippedSync: true,
    };
  }

  const url = assertSafeUrl(
    joinUrl(base, (config.employeesPath as string) || '/v1/directories/employees/list'),
    'ՀԾ Armsoft employees URL',
  );

  // ArmSoft API requires POST with empty body for employee list
  let response: Response;
  try {
    response = await fetch(url, {
      method: 'POST',
      headers: {
        ...headers,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({}),
      signal: AbortSignal.timeout(20_000),
    });
  } catch (e: unknown) {
    const reason =
      e && typeof e === 'object' && 'name' in e && (e as { name: string }).name === 'TimeoutError'
        ? 'request timed out'
        : 'network error';
    throw new Error(`ՀԾ Armsoft: ${reason}`);
  }

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`ՀԾ Armsoft API error (${response.status}): ${body.slice(0, 300)}`);
  }

  // Actions lose the runMutation type bridge, so annotate the batch result the
  // internal mutation is known to return (see upsertEmployeeBatch).
  const payload: unknown = await response.json();
  const rows = extractList(payload, config.employeesListKey as string | undefined);
  const { employees, dropped } = normalizeEmployees(rows, config.fieldMap as string | undefined);

  if (employees.length === 0) {
    throw new Error(
      `ՀԾ Armsoft: fetched ${rows.length} record(s) but none had a usable email — check the field mapping`,
    );
  }

  let created = 0;
  let updated = 0;
  let skipped = dropped;

  for (let i = 0; i < employees.length; i += UPSERT_BATCH_SIZE) {
    const batch = employees.slice(i, i + UPSERT_BATCH_SIZE);
    const res = (await ctx.runMutation(internal.integrations.upsertEmployeeBatch, {
      organizationId,
      provider: 'armsoft',
      employees: batch,
    })) as { created: number; updated: number; skipped: number; notes: string[] };
    created += res.created;
    updated += res.updated;
    skipped += res.skipped;
    notes.push(...res.notes);
  }

  const message = [
    `ՀԾ Armsoft: ${created} created, ${updated} updated, ${skipped} skipped`,
    ...notes,
  ].join('; ');
  return {
    message,
    created,
    updated,
    deactivated: 0,
    skipped,
    details: notes.length ? JSON.stringify(notes.slice(0, 50)) : undefined,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// SCHEDULED SYNC
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Cron field matcher supporting wildcards, step values, ranges, comma lists
 * and plain numbers — the subset covering every schedule the UI suggests.
 */
function cronFieldMatches(field: string, value: number, min: number, max: number): boolean {
  for (const part of field.split(',')) {
    const token = part.trim();
    if (!token) return false;

    const [rangePart, stepPart] = token.split('/');
    const step = stepPart === undefined ? 1 : Number(stepPart);
    if (!Number.isInteger(step) || step < 1) return false;

    let from = min;
    let to = max;
    if (rangePart !== '*') {
      if (rangePart!.includes('-')) {
        const [a, b] = rangePart!.split('-').map(Number);
        if (!Number.isInteger(a) || !Number.isInteger(b)) return false;
        from = a!;
        to = b!;
      } else {
        const exact = Number(rangePart);
        if (!Number.isInteger(exact)) return false;
        from = exact;
        to = stepPart === undefined ? exact : max;
      }
    }
    if (from < min || to > max || from > to) return false;
    if (value < from || value > to) continue;
    if ((value - from) % step === 0) return true;
  }
  return false;
}

export function isValidCronExpression(expr: string): boolean {
  const fields = expr.trim().split(/\s+/);
  if (fields.length !== 5) return false;
  const bounds: Array<[number, number]> = [
    [0, 59],
    [0, 23],
    [1, 31],
    [1, 12],
    [0, 6],
  ];
  // A field is valid if it matches at least one value in its range.
  return fields.every((field, i) => {
    const [min, max] = bounds[i]!;
    for (let v = min; v <= max; v++) {
      if (cronFieldMatches(field, v, min, max)) return true;
    }
    return false;
  });
}

/**
 * Whether a cron expression is due for the UTC hour containing `now`.
 *
 * The sweep runs hourly, so scheduling resolution is one hour: the minute
 * field is validated but not used to delay within the hour.
 */
export function isCronDueThisHour(expr: string, now: Date): boolean {
  const fields = expr.trim().split(/\s+/);
  if (fields.length !== 5) return false;
  const [, hour, dayOfMonth, month, dayOfWeek] = fields as [string, string, string, string, string];

  if (!cronFieldMatches(hour, now.getUTCHours(), 0, 23)) return false;
  if (!cronFieldMatches(month, now.getUTCMonth() + 1, 1, 12)) return false;

  // Standard cron: when both day fields are restricted, either may match.
  const domRestricted = dayOfMonth.trim() !== '*';
  const dowRestricted = dayOfWeek.trim() !== '*';
  const domMatch = cronFieldMatches(dayOfMonth, now.getUTCDate(), 1, 31);
  const dowMatch = cronFieldMatches(dayOfWeek, now.getUTCDay(), 0, 6);

  if (domRestricted && dowRestricted) return domMatch || dowMatch;
  if (domRestricted) return domMatch;
  if (dowRestricted) return dowMatch;
  return true;
}

/** Default schedule when an admin enabled auto-sync but set no cron. */
const DEFAULT_SYNC_CRON = '0 3 * * *';

/** Configs eligible for scheduled syncing, per provider. */
export const listEnabledConfigs = internalQuery({
  args: { provider: providerValidator },
  handler: async (ctx, { provider }) => {
    const docsRaw = await ctx.db
      .query('integrationConfigs')
      .withIndex('by_provider_enabled', (q) =>
        q.eq('provider', provider).eq('config.isEnabled', true),
      )
      .take(DEFAULT_LIST_CAP + 1);
    const isCappedDocs = docsRaw.length > DEFAULT_LIST_CAP;
    void isCappedDocs;
    const docs = docsRaw.slice(0, DEFAULT_LIST_CAP);

    return docs.map((d) => ({
      organizationId: d.organizationId,
      provider: d.provider,
      syncSchedule: d.config.syncSchedule,
      lastSyncAt: d.config.lastSyncAt,
      autoSyncEmployees: d.config.autoSyncEmployees,
      syncEmployees: d.config.syncEmployees,
      syncPayroll: d.config.syncPayroll,
    }));
  },
});

/**
 * Hourly sweep that runs every due integration sync.
 *
 * Only providers that actually import data are swept — imID holds no directory,
 * so re-authenticating it on a timer would be pointless traffic.
 */
export const runScheduledSyncs = internalAction({
  args: {},
  handler: async (ctx) => {
    const now = new Date();
    let ran = 0;
    let failed = 0;

    for (const provider of ['lucky_carrot', 'armsoft'] as const) {
      const configs = await ctx.runQuery(internal.integrations.listEnabledConfigs, { provider });

      for (const cfg of configs) {
        // Respect the per-provider "import data" switches.
        const importEnabled =
          provider === 'lucky_carrot'
            ? cfg.autoSyncEmployees === true
            : cfg.syncEmployees === true || cfg.syncPayroll === true;
        if (!importEnabled) continue;

        const schedule = cfg.syncSchedule || DEFAULT_SYNC_CRON;
        if (!isCronDueThisHour(schedule, now)) continue;

        // Guard against a double-run inside the same hour (retries, overlap).
        if (cfg.lastSyncAt && now.getTime() - cfg.lastSyncAt < 55 * 60 * 1000) continue;

        const result = await runSync(ctx, cfg.organizationId, provider);
        ran++;
        if (!result.success) failed++;
      }
    }

    return { ran, failed };
  },
});
