const fs = require('fs');
const path = require('path');

// Read all translation files
const enPath = path.join(__dirname, 'src', 'i18n', 'locales', 'en.json');
const ruPath = path.join(__dirname, 'src', 'i18n', 'locales', 'ru.json');
const hyPath = path.join(__dirname, 'src', 'i18n', 'locales', 'hy.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const ru = JSON.parse(fs.readFileSync(ruPath, 'utf8'));
const hy = JSON.parse(fs.readFileSync(hyPath, 'utf8'));

function setNested(obj, path, value) {
  const keys = path.split('.');
  const lastKey = keys.pop();
  const target = keys.reduce((o, key) => {
    if (!o[key]) o[key] = {};
    return o[key];
  }, obj);
  target[lastKey] = value;
}

// Armenian translations for untranslated keys
const hyTranslations = {
  'ui.backToLogin': 'Հետ մուտք',
  'tasks.today': 'Այսօր',
  'tasks.tomorrow': 'Վաղը',
  'tasks.overdue': 'Ժամկետանց',
  'tasks.topPriority': 'Բարձր առաջնահերթության խնդիրներ',
  'tasks.quickAccess': 'Արագ մուտք դեպի ձեր կարևոր խնդիրներ',
  'superadmin.creatingOrg': 'Ստեղծվում է {{name}} կազմակերպությունը...',
  'superadmin.orgCreated': '"{{name}}" կազմակերպությունը հաջողությամբ ստեղծվեց!',
  'superadmin.adminInvitationSent': 'Ադմինի հրավերը կուղարկվի {{email}}-ին',
  'superadmin.users.driversFound': '{{count}} վարորդի հայտ գտնվեց',
  'superadmin.users.noDriversFound': 'Վարորդի հայտեր չգտնվեցին',
  'superadmin.users.tabLeaves': 'Արձակուրդներ',
  'superadmin.users.tabTasks': 'Խնդիրներ',
  'superadmin.users.tabDrivers': 'Վարորդներ',
  'superadmin.users.tabTickets': 'Տոմսեր',
  'superadmin.users.tabActivity': 'Ակտիվություն',
  'superadmin.users.tabSecurity': 'Անվտանգություն',
  'superadmin.users.tabChat': 'Չատ',
  'superadmin.users.ticketsTitle': 'Աջակցության տոմսեր',
  'superadmin.users.notificationsAndActions': 'Օգտատիրոջ ծանուցումներ և գործողություններ',
  'superadmin.users.recentLogins': 'Վերջին մուտքի փորձեր',
  'auth.pending.questions': 'Հարցեր ունե՞ք:',
  'auth.pending.contactSupport': 'Կապվեք մեզ հետ',
  'auth.creatingAccount': 'Հաշիվը ստեղծվում է…',
  'auth.requestToJoin': 'Միանալու հայտ',
  'auth.findYourOrg': 'Գտեք ձեր կազմակերպությունը',
  'titles.regenerate': 'Վերագեներացնել',
  'aiSiteEditor.rollbackCompleted': '↩️ Վերականգնումն ավարտվեց {{filePath}} ֆայլի համար',
  'admin.webhooks': 'Webhooks',
  'organization.slugLabel': 'Slug',
  'organization.planEnterprise': 'Enterprise (100+)',
  'organization.timezoneUTC': 'UTC',
  'labels.url': 'URL',
  'security.riskHigh': 'ԲԱՐՁՐ',
  'security.riskMed': 'ՄԻՋԻՆ',
  'security.riskLow': 'ՑԱԾՐ',
  'security.toggleOn': 'ՄԻԱՑՎԱԾ',
  'security.toggleOff': 'ԱՆՋԱՏՎԱԾ',
  'security.autoBlocked': 'ԱՎՏՈՄԱՏ ԲԼՈԿԱՎՈՐՎԱԾ',
  'security.expiresHours': 'Ժամկետը լրանում է {{hours}} ժ-ից',
  'security.suspendedUntil': 'Մինչև',
  'security.hoursOne': '1',
  'security.hoursTwentyFour': '24',
  'security.riskLabelHigh': 'ԲԱՐՁՐ ՌԻՍԿ',
  'security.riskLabelModerate': 'ՉԱՓԱՎՈՐ',
  'security.riskLabelLow': 'ՑԱԾՐ',
  'stripeDashboard.mrr': 'MRR',
  'createOrganization.utc': 'UTC',
  'driver.timeValidation.en': '🇬🇧 Սկսման ժամանակը պետք է ավելի վաղ լինի, քան ավարտը',
  'driver.timeValidation.ru': '🇷🇺 Время начала должно быть раньше времени окончания',
  'driver.timeValidation.hy': '🇦🇲 Սկսման ժամանակը պետք է ավելի վաղ լինի, քան ավարտը',
  'driver.navigator.google': 'Google Maps',
  'driver.navigator.yandex': 'Yandex Maps',
  'driver.navigator.2gis': '2GIS',
  'driver.navigator.waze': 'Waze',
  'driver.navigator.apple': 'Apple Maps',
  'aiChat.title': 'Shield HR AI',
  'registerOrg.phonePlaceholder': '+1 234 567 890',
  'plan.enterprise100Plus': 'Enterprise (100+)',
  'toasts.ip': 'IP',
  'driversWizard.makePlaceholder': 'Toyota',
  'driversWizard.modelPlaceholder': 'Camry',
  'driversWizard.yearPlaceholder': '2024',
  'driversWizard.decrease': '-',
  'driversWizard.increase': '+',
  'driversWizard.suv': 'SUV',
  'localizationSettings.english': '🇺🇸 English',
  'localizationSettings.spanish': '🇪🇸 Español',
  'localizationSettings.french': '🇫🇷 Français',
  'localizationSettings.german': '🇩🇪 Deutsch',
  'localizationSettings.chinese': '🇨🇳 中文',
  'localizationSettings.japanese': '🇯🇵 日本語',
  'localizationSettings.arabic': '🇸🇦 العربية',
  'localizationSettings.utc': 'UTC (GMT+0)',
  'localizationSettings.dateFormatDDMM': 'DD/MM/YYYY (25/12/2024)',
  'localizationSettings.dateFormatMMDD': 'MM/DD/YYYY (12/25/2024)',
  'localizationSettings.dateFormatYYYY': 'YYYY-MM-DD (2024-12-25)',
  'localizationSettings.dateFormatDDMMYY': 'DD.MM.YYYY (25.12.2024)',
  'settingsIntegration.microsoftSharePoint': 'Microsoft SharePoint',
  'settingsIntegration.microsoftTeams': 'Microsoft Teams',
  'settingsIntegration.slack': 'Slack',
  'billing.paypal': 'PayPal',
  'billing.stripe': 'Stripe',
  'exportData.csv': 'CSV',
  'exportData.excel': 'Excel',
  'exportData.pdf': 'PDF',
  'exportData.json': 'JSON',
  'exportData.xml': 'XML',
  'subscriptions.stripe': 'Stripe',
  'stripe.mrr': 'MRR',
  'statistics.kpi': 'KPI',
  'sidebar.appName': 'HR Office',
  'employeeInfo.email': 'Email',
  'contact.email': 'Email',
  'legal.legalEmail': 'legal@shieldoffice.com',
  'legal.privacyEmail': 'privacy@shieldoffice.com',
  'impersonate.email': 'Email:',
  'currency.usd': '$',
  'currency.eur': '€',
  'currency.rub': '₽',
  'placeholders.acmeCorp': 'Acme Corp',
  'placeholders.acmeCorporation': 'Acme Corporation',
  'placeholders.acmeInc': 'acme-inc',
  'placeholders.auraMedicalCenter': 'Aura Medical Center',
  'placeholders.enterYourEmail': 'admin@example.com',
  'placeholders.youAtCompany': 'you@company.com',
  'placeholders.emailAddress': 'you@company.com',
  'departments.hr': 'HR',
  'departments.it': 'IT',
  'labels.email': 'Email',
  'help.quickHelp.email.title': 'Email',
  'help.quickHelp.email.desc': 'support@example.com',
  'pricing.starterPrice': '$29',
  'pricing.professionalPrice': '$79',
  'auth.phonePlaceholder': '+374 XX XXX XXX',
  'common.hrOffice': 'HR Office',
  'common.noopenerNoreferrer': 'noopener noreferrer',
  'landing.hrLeave': 'HR Office',
  'landingExtra.footerGdpr': 'GDPR',
  'auth.faceId': 'Face ID',
  'auth.hrOffice': 'HR Office',
  'dashboard.kpi': 'KPI',
  'settingsSecurity.touchId': 'Touch ID / Fingerprint',
  'settingsSecurity.faceId': 'Face ID',
  'settingsAdvancedSecurity.twoFactorDesc': 'Ավելացրեք անվտանգության լրացուցիչ շերտ ձեր հաշվին',
  'settingsAdvancedSecurity.enable2faDesc': 'Պահանջեք ստուգման կոդ գաղտնաբառից բացի',
  'settingsAdvancedSecurity.choose2fa': 'Ընտրեք 2FA մեթոդ:',
  'settingsAdvancedSecurity.smsSms': 'SMS տեքստային հաղորդագրություն',
  'settingsAdvancedSecurity.emailCode': 'Email կոդ',
  'settingsAdvancedSecurity.authenticatorApp': 'Authenticator հավելված (Google, Microsoft)',
  'organization.slugLabel': 'Slug',
  'sidebar.orgSubtitle': 'HR Կառավարում',
  'sidebar.orgSubtitleFull': 'HR Կառավարման Համակարգ'
};

// Russian translations for untranslated keys
const ruTranslations = {
  'ui.backToLogin': 'Назад к входу',
  'tasks.today': 'Сегодня',
  'tasks.tomorrow': 'Завтра',
  'tasks.overdue': 'Просрочено',
  'tasks.topPriority': 'Задачи высшего приоритета',
  'tasks.quickAccess': 'Быстрый доступ к важным задачам',
  'superadmin.creatingOrg': 'Создание организации {{name}}...',
  'superadmin.orgCreated': 'Организация "{{name}}" успешно создана!',
  'superadmin.adminInvitationSent': 'Приглашение администратора будет отправлено на {{email}}',
  'superadmin.users.driversFound': 'Найдено {{count}} запросов водителей',
  'superadmin.users.noDriversFound': 'Запросы водителей не найдены',
  'superadmin.users.tabLeaves': 'Отпуска',
  'superadmin.users.tabTasks': 'Задачи',
  'superadmin.users.tabDrivers': 'Водители',
  'superadmin.users.tabTickets': 'Тикеты',
  'superadmin.users.tabActivity': 'Активность',
  'superadmin.users.tabSecurity': 'Безопасность',
  'superadmin.users.tabChat': 'Чат',
  'superadmin.users.ticketsTitle': 'Тикеты поддержки',
  'superadmin.users.notificationsAndActions': 'Уведомления и действия пользователя',
  'superadmin.users.recentLogins': 'Последние попытки входа',
  'auth.pending.questions': 'Вопросы?',
  'auth.pending.contactSupport': 'Свяжитесь с нами',
  'auth.creatingAccount': 'Создание аккаунта…',
  'auth.requestToJoin': 'Запрос на присоединение',
  'auth.findYourOrg': 'Найдите вашу организацию',
  'titles.regenerate': 'Перегенерировать',
  'aiSiteEditor.rollbackCompleted': '↩️ Откат завершен для файла {{filePath}}',
  'admin.webhooks': 'Webhooks',
  'organization.slugLabel': 'Slug',
  'organization.planEnterprise': 'Enterprise (100+)',
  'organization.timezoneUTC': 'UTC',
  'labels.url': 'URL',
  'security.riskHigh': 'ВЫСОКИЙ',
  'security.riskMed': 'СРЕДНИЙ',
  'security.riskLow': 'НИЗКИЙ',
  'security.toggleOn': 'ВКЛ',
  'security.toggleOff': 'ВЫКЛ',
  'security.autoBlocked': 'АВТОБЛОКИРОВКА',
  'security.expiresHours': 'Истекает через {{hours}} ч',
  'security.suspendedUntil': 'До',
  'security.hoursOne': '1',
  'security.hoursTwentyFour': '24',
  'security.riskLabelHigh': 'ВЫСОКИЙ РИСК',
  'security.riskLabelModerate': 'УМЕРЕННЫЙ',
  'security.riskLabelLow': 'НИЗКИЙ',
  'stripeDashboard.mrr': 'MRR',
  'createOrganization.utc': 'UTC',
  'driver.timeValidation.en': '🇬🇧 Start time must be earlier than end time',
  'driver.navigator.google': 'Google Maps',
  'driver.navigator.yandex': 'Yandex Maps',
  'driver.navigator.2gis': '2GIS',
  'driver.navigator.waze': 'Waze',
  'driver.navigator.apple': 'Apple Maps',
  'aiChat.title': 'Shield HR AI',
  'registerOrg.phonePlaceholder': '+1 234 567 890',
  'plan.enterprise100Plus': 'Enterprise (100+)',
  'toasts.ip': 'IP',
  'driversWizard.makePlaceholder': 'Toyota',
  'driversWizard.modelPlaceholder': 'Camry',
  'driversWizard.yearPlaceholder': '2024',
  'driversWizard.decrease': '-',
  'driversWizard.increase': '+',
  'driversWizard.suv': 'SUV',
  'localizationSettings.english': '🇺🇸 English',
  'localizationSettings.spanish': '🇪🇸 Español',
  'localizationSettings.french': '🇫🇷 Français',
  'localizationSettings.german': '🇩🇪 Deutsch',
  'localizationSettings.chinese': '🇨🇳 中文',
  'localizationSettings.japanese': '🇯🇵 日本語',
  'localizationSettings.arabic': '🇸🇦 العربية',
  'localizationSettings.utc': 'UTC (GMT+0)',
  'localizationSettings.dateFormatDDMM': 'DD/MM/YYYY (25/12/2024)',
  'localizationSettings.dateFormatMMDD': 'MM/DD/YYYY (12/25/2024)',
  'localizationSettings.dateFormatYYYY': 'YYYY-MM-DD (2024-12-25)',
  'localizationSettings.dateFormatDDMMYY': 'DD.MM.YYYY (25.12.2024)',
  'settingsIntegration.microsoftSharePoint': 'Microsoft SharePoint',
  'settingsIntegration.microsoftTeams': 'Microsoft Teams',
  'settingsIntegration.slack': 'Slack',
  'billing.paypal': 'PayPal',
  'billing.stripe': 'Stripe',
  'exportData.csv': 'CSV',
  'exportData.excel': 'Excel',
  'exportData.pdf': 'PDF',
  'exportData.json': 'JSON',
  'exportData.xml': 'XML',
  'subscriptions.stripe': 'Stripe',
  'stripe.mrr': 'MRR',
  'statistics.kpi': 'KPI',
  'sidebar.appName': 'HR Office',
  'sidebar.orgSubtitle': 'Управление HR',
  'sidebar.orgSubtitleFull': 'Система управления HR',
  'employeeInfo.email': 'Email',
  'contact.email': 'Email',
  'legal.legalEmail': 'legal@shieldoffice.com',
  'legal.privacyEmail': 'privacy@shieldoffice.com',
  'impersonate.email': 'Email:',
  'labels.email': 'Email',
  'help.quickHelp.email.title': 'Email',
  'help.quickHelp.email.desc': 'support@example.com',
  'auth.faceId': 'Face ID',
  'dashboard.kpi': 'KPI',
  'settingsSecurity.touchId': 'Touch ID / Отпечаток пальца',
  'settingsSecurity.faceId': 'Face ID'
};

// Apply translations
let addedHy = 0;
let addedRu = 0;

for (const [key, value] of Object.entries(hyTranslations)) {
  setNested(hy, key, value);
  addedHy++;
}

for (const [key, value] of Object.entries(ruTranslations)) {
  setNested(ru, key, value);
  addedRu++;
}

// Write updated files
fs.writeFileSync(hyPath, JSON.stringify(hy, null, 2) + '\n', 'utf8');
fs.writeFileSync(ruPath, JSON.stringify(ru, null, 2) + '\n', 'utf8');

console.log(`\n✅ Complete!`);
console.log(`Added ${addedHy} Armenian translations`);
console.log(`Added ${addedRu} Russian translations`);
console.log('\nFiles updated:');
console.log('- src/i18n/locales/hy.json');
console.log('- src/i18n/locales/ru.json');
