/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as admin from "../admin.js";
import type * as aiChat from "../aiChat.js";
import type * as aiChatMutations from "../aiChatMutations.js";
import type * as aiEvaluator from "../aiEvaluator.js";
import type * as aiGovernance from "../aiGovernance.js";
import type * as aiMemory from "../aiMemory.js";
import type * as aiSiteEditor from "../aiSiteEditor.js";
import type * as analytics from "../analytics.js";
import type * as assets from "../assets.js";
import type * as attendance_bot from "../attendance/bot.js";
import type * as attendance_index from "../attendance/index.js";
import type * as attendance_mutations from "../attendance/mutations.js";
import type * as attendance_queries from "../attendance/queries.js";
import type * as attritionRisk from "../attritionRisk.js";
import type * as auth from "../auth.js";
import type * as auth_module_index from "../auth_module/index.js";
import type * as auth_module_main from "../auth_module/main.js";
import type * as automation from "../automation.js";
import type * as automationActions from "../automationActions.js";
import type * as automationMutations from "../automationMutations.js";
import type * as backups from "../backups.js";
import type * as badges from "../badges.js";
import type * as billing_defaults from "../billing/defaults.js";
import type * as billing_modules from "../billing/modules.js";
import type * as billing_plans from "../billing/plans.js";
import type * as billing_seed from "../billing/seed.js";
import type * as birthdays from "../birthdays.js";
import type * as branding from "../branding.js";
import type * as calendarEvents from "../calendarEvents.js";
import type * as candidatePortal from "../candidatePortal.js";
import type * as careers from "../careers.js";
import type * as chat from "../chat.js";
import type * as chat_calls from "../chat/calls.js";
import type * as chat_index from "../chat/index.js";
import type * as chat_mutations from "../chat/mutations.js";
import type * as chat_presence from "../chat/presence.js";
import type * as chat_queries from "../chat/queries.js";
import type * as chatAction from "../chatAction.js";
import type * as compensation from "../compensation.js";
import type * as compliance from "../compliance.js";
import type * as conflicts from "../conflicts.js";
import type * as conflicts_index from "../conflicts/index.js";
import type * as conflicts_main from "../conflicts/main.js";
import type * as corporate from "../corporate.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as departments from "../departments.js";
import type * as documentBlueprints from "../documentBlueprints.js";
import type * as documentLibrary from "../documentLibrary.js";
import type * as documents from "../documents.js";
import type * as driverAI from "../driverAI.js";
import type * as drivers from "../drivers.js";
import type * as drivers_calendar_mutations from "../drivers/calendar_mutations.js";
import type * as drivers_calendar_queries from "../drivers/calendar_queries.js";
import type * as drivers_driver_operations from "../drivers/driver_operations.js";
import type * as drivers_driver_registration from "../drivers/driver_registration.js";
import type * as drivers_queries from "../drivers/queries.js";
import type * as drivers_recurring_trips from "../drivers/recurring_trips.js";
import type * as drivers_requests_mutations from "../drivers/requests_mutations.js";
import type * as drivers_requests_queries from "../drivers/requests_queries.js";
import type * as drivers_shifts_mutations from "../drivers/shifts_mutations.js";
import type * as emailValidation from "../emailValidation.js";
import type * as employeeExtendedProfile from "../employeeExtendedProfile.js";
import type * as employeeNotes from "../employeeNotes.js";
import type * as employeeProfiles from "../employeeProfiles.js";
import type * as events from "../events.js";
import type * as expenses from "../expenses.js";
import type * as faceRecognition from "../faceRecognition.js";
import type * as goals from "../goals.js";
import type * as hiringPackets from "../hiringPackets.js";
import type * as hrCronJobs from "../hrCronJobs.js";
import type * as http from "../http.js";
import type * as integrations from "../integrations.js";
import type * as issuedDocuments from "../issuedDocuments.js";
import type * as landing from "../landing.js";
import type * as learning from "../learning.js";
import type * as leaveAccrual from "../leaveAccrual.js";
import type * as leaveSettings from "../leaveSettings.js";
import type * as leaves from "../leaves.js";
import type * as leaves_approval from "../leaves/approval.js";
import type * as leaves_balances from "../leaves/balances.js";
import type * as leaves_documents from "../leaves/documents.js";
import type * as leaves_helpers from "../leaves/helpers.js";
import type * as leaves_index from "../leaves/index.js";
import type * as leaves_mutations from "../leaves/mutations.js";
import type * as leaves_queries from "../leaves/queries.js";
import type * as lib_appErrors from "../lib/appErrors.js";
import type * as lib_attritionScoring from "../lib/attritionScoring.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_capabilities from "../lib/capabilities.js";
import type * as lib_date from "../lib/date.js";
import type * as lib_device from "../lib/device.js";
import type * as lib_documentNumbers from "../lib/documentNumbers.js";
import type * as lib_documentTemplateIds from "../lib/documentTemplateIds.js";
import type * as lib_driverEligibility from "../lib/driverEligibility.js";
import type * as lib_entitlements from "../lib/entitlements.js";
import type * as lib_getAuthCaller from "../lib/getAuthCaller.js";
import type * as lib_i18n from "../lib/i18n.js";
import type * as lib_leaveBalances from "../lib/leaveBalances.js";
import type * as lib_leaveMoney from "../lib/leaveMoney.js";
import type * as lib_leaveTypes from "../lib/leaveTypes.js";
import type * as lib_limits from "../lib/limits.js";
import type * as lib_localeCatalog from "../lib/localeCatalog.js";
import type * as lib_notify from "../lib/notify.js";
import type * as lib_orderKey from "../lib/orderKey.js";
import type * as lib_orgAccess from "../lib/orgAccess.js";
import type * as lib_orgDays from "../lib/orgDays.js";
import type * as lib_orgUnits from "../lib/orgUnits.js";
import type * as lib_payrollCalculator from "../lib/payrollCalculator.js";
import type * as lib_pension from "../lib/pension.js";
import type * as lib_points from "../lib/points.js";
import type * as lib_rbac from "../lib/rbac.js";
import type * as lib_recurrence from "../lib/recurrence.js";
import type * as lib_reportingLine from "../lib/reportingLine.js";
import type * as lib_resolveServiceAssignee from "../lib/resolveServiceAssignee.js";
import type * as lib_sanitize from "../lib/sanitize.js";
import type * as lib_sha256 from "../lib/sha256.js";
import type * as lib_systemAccounts from "../lib/systemAccounts.js";
import type * as lib_systemMessage from "../lib/systemMessage.js";
import type * as lib_taskAccess from "../lib/taskAccess.js";
import type * as lib_taskConfig from "../lib/taskConfig.js";
import type * as lib_taskCustomFields from "../lib/taskCustomFields.js";
import type * as lib_taskStatus from "../lib/taskStatus.js";
import type * as lib_taxRules from "../lib/taxRules.js";
import type * as lib_ticketFields from "../lib/ticketFields.js";
import type * as lib_travelAllowance from "../lib/travelAllowance.js";
import type * as lib_userProfile from "../lib/userProfile.js";
import type * as lib_userRedaction from "../lib/userRedaction.js";
import type * as lib_webhookEvents from "../lib/webhookEvents.js";
import type * as meetingRooms from "../meetingRooms.js";
import type * as meetings from "../meetings.js";
import type * as meetingsActions from "../meetingsActions.js";
import type * as messenger_calls from "../messenger/calls.js";
import type * as messenger_conversations from "../messenger/conversations.js";
import type * as messenger_index from "../messenger/index.js";
import type * as messenger_messages from "../messenger/messages.js";
import type * as messenger_search from "../messenger/search.js";
import type * as messenger_threads from "../messenger/threads.js";
import type * as messenger_typing from "../messenger/typing.js";
import type * as messenger_unread from "../messenger/unread.js";
import type * as migrations from "../migrations.js";
import type * as migrations_orgUnits from "../migrations_orgUnits.js";
import type * as news from "../news.js";
import type * as newsSchedule from "../newsSchedule.js";
import type * as newsletter from "../newsletter.js";
import type * as notifications from "../notifications.js";
import type * as offboarding from "../offboarding.js";
import type * as onboarding from "../onboarding.js";
import type * as organizationJoinRequests from "../organizationJoinRequests.js";
import type * as organizationRequests from "../organizationRequests.js";
import type * as organizations from "../organizations.js";
import type * as organizations_index from "../organizations/index.js";
import type * as organizations_main from "../organizations/main.js";
import type * as orgchart from "../orgchart.js";
import type * as overtime from "../overtime.js";
import type * as overtime_index from "../overtime/index.js";
import type * as overtime_mutations from "../overtime/mutations.js";
import type * as overtime_queries from "../overtime/queries.js";
import type * as overtime_settings from "../overtime/settings.js";
import type * as pagination from "../pagination.js";
import type * as payments from "../payments.js";
import type * as payroll_actions from "../payroll/actions.js";
import type * as payroll_index from "../payroll/index.js";
import type * as payroll_mutations from "../payroll/mutations.js";
import type * as payroll_queries from "../payroll/queries.js";
import type * as performance from "../performance.js";
import type * as positions from "../positions.js";
import type * as probation from "../probation.js";
import type * as productivity from "../productivity.js";
import type * as projects from "../projects.js";
import type * as recognition from "../recognition.js";
import type * as recruitment from "../recruitment.js";
import type * as recruitmentAI from "../recruitmentAI.js";
import type * as recruitmentEmails from "../recruitmentEmails.js";
import type * as recurringTasks from "../recurringTasks.js";
import type * as reporting from "../reporting.js";
import type * as rewards from "../rewards.js";
import type * as schema_ai from "../schema/ai.js";
import type * as schema_aiGovernance from "../schema/aiGovernance.js";
import type * as schema_analytics from "../schema/analytics.js";
import type * as schema_assets from "../schema/assets.js";
import type * as schema_attendance from "../schema/attendance.js";
import type * as schema_automation from "../schema/automation.js";
import type * as schema_backups from "../schema/backups.js";
import type * as schema_billing from "../schema/billing.js";
import type * as schema_calendar from "../schema/calendar.js";
import type * as schema_chat from "../schema/chat.js";
import type * as schema_compensation from "../schema/compensation.js";
import type * as schema_compliance from "../schema/compliance.js";
import type * as schema_conflicts from "../schema/conflicts.js";
import type * as schema_corporate from "../schema/corporate.js";
import type * as schema_departments from "../schema/departments.js";
import type * as schema_documentBuilder from "../schema/documentBuilder.js";
import type * as schema_documents from "../schema/documents.js";
import type * as schema_drivers from "../schema/drivers.js";
import type * as schema_employees from "../schema/employees.js";
import type * as schema_events from "../schema/events.js";
import type * as schema_expenses from "../schema/expenses.js";
import type * as schema_goals from "../schema/goals.js";
import type * as schema_hiringPackets from "../schema/hiringPackets.js";
import type * as schema_index from "../schema/index.js";
import type * as schema_integrations from "../schema/integrations.js";
import type * as schema_landing from "../schema/landing.js";
import type * as schema_landingTexts from "../schema/landingTexts.js";
import type * as schema_learning from "../schema/learning.js";
import type * as schema_leaveSettings from "../schema/leaveSettings.js";
import type * as schema_leaves from "../schema/leaves.js";
import type * as schema_meetingRooms from "../schema/meetingRooms.js";
import type * as schema_meetings from "../schema/meetings.js";
import type * as schema_messenger from "../schema/messenger.js";
import type * as schema_news from "../schema/news.js";
import type * as schema_newsletter from "../schema/newsletter.js";
import type * as schema_notifications from "../schema/notifications.js";
import type * as schema_offboarding from "../schema/offboarding.js";
import type * as schema_onboarding from "../schema/onboarding.js";
import type * as schema_operatorTools from "../schema/operatorTools.js";
import type * as schema_organizations from "../schema/organizations.js";
import type * as schema_orgchart from "../schema/orgchart.js";
import type * as schema_overtime from "../schema/overtime.js";
import type * as schema_payroll from "../schema/payroll.js";
import type * as schema_performance from "../schema/performance.js";
import type * as schema_positions from "../schema/positions.js";
import type * as schema_probation from "../schema/probation.js";
import type * as schema_productivity from "../schema/productivity.js";
import type * as schema_projects from "../schema/projects.js";
import type * as schema_recognition from "../schema/recognition.js";
import type * as schema_recruitment from "../schema/recruitment.js";
import type * as schema_rewards from "../schema/rewards.js";
import type * as schema_scim from "../schema/scim.js";
import type * as schema_security from "../schema/security.js";
import type * as schema_settings from "../schema/settings.js";
import type * as schema_shifts from "../schema/shifts.js";
import type * as schema_signatures from "../schema/signatures.js";
import type * as schema_sla from "../schema/sla.js";
import type * as schema_sso from "../schema/sso.js";
import type * as schema_surveys from "../schema/surveys.js";
import type * as schema_tasks from "../schema/tasks.js";
import type * as schema_tickets from "../schema/tickets.js";
import type * as schema_userProfiles from "../schema/userProfiles.js";
import type * as schema_userSettings from "../schema/userSettings.js";
import type * as schema_users from "../schema/users.js";
import type * as schema_webhooks from "../schema/webhooks.js";
import type * as scim_main from "../scim/main.js";
import type * as scripts_auditTestData from "../scripts/auditTestData.js";
import type * as scripts_cleanupQaData from "../scripts/cleanupQaData.js";
import type * as scripts_cleanupQaResidual from "../scripts/cleanupQaResidual.js";
import type * as scripts_createTestAutomationData from "../scripts/createTestAutomationData.js";
import type * as scripts_createTestTicket from "../scripts/createTestTicket.js";
import type * as security from "../security.js";
import type * as settings from "../settings.js";
import type * as settlement from "../settlement.js";
import type * as sharepointSync from "../sharepointSync.js";
import type * as shifts from "../shifts.js";
import type * as signatures from "../signatures.js";
import type * as sla from "../sla.js";
import type * as sso_actions from "../sso/actions.js";
import type * as sso_flows from "../sso/flows.js";
import type * as sso_main from "../sso/main.js";
import type * as sso_protocol from "../sso/protocol.js";
import type * as strategyMaps from "../strategyMaps.js";
import type * as subscriptions from "../subscriptions.js";
import type * as subscriptions_admin from "../subscriptions_admin.js";
import type * as superadmin from "../superadmin.js";
import type * as superadmin_accessMatrix from "../superadmin/accessMatrix.js";
import type * as superadmin_accessTokens from "../superadmin/accessTokens.js";
import type * as superadmin_controlCenter from "../superadmin/controlCenter.js";
import type * as superadmin_dbAdmin from "../superadmin/dbAdmin.js";
import type * as superadmin_emergency from "../superadmin/emergency.js";
import type * as superadmin_featureToggles from "../superadmin/featureToggles.js";
import type * as superadmin_gdprToolkit from "../superadmin/gdprToolkit.js";
import type * as superadmin_hub from "../superadmin/hub.js";
import type * as superadmin_impersonation from "../superadmin/impersonation.js";
import type * as superadmin_index from "../superadmin/index.js";
import type * as superadmin_landingEditor from "../superadmin/landingEditor.js";
import type * as superadmin_operatorTools from "../superadmin/operatorTools.js";
import type * as superadmin_operatorToolsInternal from "../superadmin/operatorToolsInternal.js";
import type * as superadmin_organizations from "../superadmin/organizations.js";
import type * as superadmin_search from "../superadmin/search.js";
import type * as superadmin_sessions from "../superadmin/sessions.js";
import type * as superadmin_tempPasswords from "../superadmin/tempPasswords.js";
import type * as superadmin_terminal from "../superadmin/terminal.js";
import type * as superadmin_trash from "../superadmin/trash.js";
import type * as superadmin_user360 from "../superadmin/user360.js";
import type * as supervisorRatings from "../supervisorRatings.js";
import type * as surveys from "../surveys.js";
import type * as taskFields from "../taskFields.js";
import type * as taskRelations from "../taskRelations.js";
import type * as taskStatuses from "../taskStatuses.js";
import type * as taskTime from "../taskTime.js";
import type * as taskViews from "../taskViews.js";
import type * as tasks from "../tasks.js";
import type * as telegram from "../telegram.js";
import type * as tickets from "../tickets.js";
import type * as timeTracking from "../timeTracking.js";
import type * as updateSuperadminPlan from "../updateSuperadminPlan.js";
import type * as userPreferences from "../userPreferences.js";
import type * as userStats from "../userStats.js";
import type * as users from "../users.js";
import type * as users_admin from "../users/admin.js";
import type * as users_auth from "../users/auth.js";
import type * as users_index from "../users/index.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as webhooks_main from "../webhooks/main.js";
import type * as webhooks_protocol from "../webhooks/protocol.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  admin: typeof admin;
  aiChat: typeof aiChat;
  aiChatMutations: typeof aiChatMutations;
  aiEvaluator: typeof aiEvaluator;
  aiGovernance: typeof aiGovernance;
  aiMemory: typeof aiMemory;
  aiSiteEditor: typeof aiSiteEditor;
  analytics: typeof analytics;
  assets: typeof assets;
  "attendance/bot": typeof attendance_bot;
  "attendance/index": typeof attendance_index;
  "attendance/mutations": typeof attendance_mutations;
  "attendance/queries": typeof attendance_queries;
  attritionRisk: typeof attritionRisk;
  auth: typeof auth;
  "auth_module/index": typeof auth_module_index;
  "auth_module/main": typeof auth_module_main;
  automation: typeof automation;
  automationActions: typeof automationActions;
  automationMutations: typeof automationMutations;
  backups: typeof backups;
  badges: typeof badges;
  "billing/defaults": typeof billing_defaults;
  "billing/modules": typeof billing_modules;
  "billing/plans": typeof billing_plans;
  "billing/seed": typeof billing_seed;
  birthdays: typeof birthdays;
  branding: typeof branding;
  calendarEvents: typeof calendarEvents;
  candidatePortal: typeof candidatePortal;
  careers: typeof careers;
  chat: typeof chat;
  "chat/calls": typeof chat_calls;
  "chat/index": typeof chat_index;
  "chat/mutations": typeof chat_mutations;
  "chat/presence": typeof chat_presence;
  "chat/queries": typeof chat_queries;
  chatAction: typeof chatAction;
  compensation: typeof compensation;
  compliance: typeof compliance;
  conflicts: typeof conflicts;
  "conflicts/index": typeof conflicts_index;
  "conflicts/main": typeof conflicts_main;
  corporate: typeof corporate;
  crons: typeof crons;
  dashboard: typeof dashboard;
  departments: typeof departments;
  documentBlueprints: typeof documentBlueprints;
  documentLibrary: typeof documentLibrary;
  documents: typeof documents;
  driverAI: typeof driverAI;
  drivers: typeof drivers;
  "drivers/calendar_mutations": typeof drivers_calendar_mutations;
  "drivers/calendar_queries": typeof drivers_calendar_queries;
  "drivers/driver_operations": typeof drivers_driver_operations;
  "drivers/driver_registration": typeof drivers_driver_registration;
  "drivers/queries": typeof drivers_queries;
  "drivers/recurring_trips": typeof drivers_recurring_trips;
  "drivers/requests_mutations": typeof drivers_requests_mutations;
  "drivers/requests_queries": typeof drivers_requests_queries;
  "drivers/shifts_mutations": typeof drivers_shifts_mutations;
  emailValidation: typeof emailValidation;
  employeeExtendedProfile: typeof employeeExtendedProfile;
  employeeNotes: typeof employeeNotes;
  employeeProfiles: typeof employeeProfiles;
  events: typeof events;
  expenses: typeof expenses;
  faceRecognition: typeof faceRecognition;
  goals: typeof goals;
  hiringPackets: typeof hiringPackets;
  hrCronJobs: typeof hrCronJobs;
  http: typeof http;
  integrations: typeof integrations;
  issuedDocuments: typeof issuedDocuments;
  landing: typeof landing;
  learning: typeof learning;
  leaveAccrual: typeof leaveAccrual;
  leaveSettings: typeof leaveSettings;
  leaves: typeof leaves;
  "leaves/approval": typeof leaves_approval;
  "leaves/balances": typeof leaves_balances;
  "leaves/documents": typeof leaves_documents;
  "leaves/helpers": typeof leaves_helpers;
  "leaves/index": typeof leaves_index;
  "leaves/mutations": typeof leaves_mutations;
  "leaves/queries": typeof leaves_queries;
  "lib/appErrors": typeof lib_appErrors;
  "lib/attritionScoring": typeof lib_attritionScoring;
  "lib/auth": typeof lib_auth;
  "lib/capabilities": typeof lib_capabilities;
  "lib/date": typeof lib_date;
  "lib/device": typeof lib_device;
  "lib/documentNumbers": typeof lib_documentNumbers;
  "lib/documentTemplateIds": typeof lib_documentTemplateIds;
  "lib/driverEligibility": typeof lib_driverEligibility;
  "lib/entitlements": typeof lib_entitlements;
  "lib/getAuthCaller": typeof lib_getAuthCaller;
  "lib/i18n": typeof lib_i18n;
  "lib/leaveBalances": typeof lib_leaveBalances;
  "lib/leaveMoney": typeof lib_leaveMoney;
  "lib/leaveTypes": typeof lib_leaveTypes;
  "lib/limits": typeof lib_limits;
  "lib/localeCatalog": typeof lib_localeCatalog;
  "lib/notify": typeof lib_notify;
  "lib/orderKey": typeof lib_orderKey;
  "lib/orgAccess": typeof lib_orgAccess;
  "lib/orgDays": typeof lib_orgDays;
  "lib/orgUnits": typeof lib_orgUnits;
  "lib/payrollCalculator": typeof lib_payrollCalculator;
  "lib/pension": typeof lib_pension;
  "lib/points": typeof lib_points;
  "lib/rbac": typeof lib_rbac;
  "lib/recurrence": typeof lib_recurrence;
  "lib/reportingLine": typeof lib_reportingLine;
  "lib/resolveServiceAssignee": typeof lib_resolveServiceAssignee;
  "lib/sanitize": typeof lib_sanitize;
  "lib/sha256": typeof lib_sha256;
  "lib/systemAccounts": typeof lib_systemAccounts;
  "lib/systemMessage": typeof lib_systemMessage;
  "lib/taskAccess": typeof lib_taskAccess;
  "lib/taskConfig": typeof lib_taskConfig;
  "lib/taskCustomFields": typeof lib_taskCustomFields;
  "lib/taskStatus": typeof lib_taskStatus;
  "lib/taxRules": typeof lib_taxRules;
  "lib/ticketFields": typeof lib_ticketFields;
  "lib/travelAllowance": typeof lib_travelAllowance;
  "lib/userProfile": typeof lib_userProfile;
  "lib/userRedaction": typeof lib_userRedaction;
  "lib/webhookEvents": typeof lib_webhookEvents;
  meetingRooms: typeof meetingRooms;
  meetings: typeof meetings;
  meetingsActions: typeof meetingsActions;
  "messenger/calls": typeof messenger_calls;
  "messenger/conversations": typeof messenger_conversations;
  "messenger/index": typeof messenger_index;
  "messenger/messages": typeof messenger_messages;
  "messenger/search": typeof messenger_search;
  "messenger/threads": typeof messenger_threads;
  "messenger/typing": typeof messenger_typing;
  "messenger/unread": typeof messenger_unread;
  migrations: typeof migrations;
  migrations_orgUnits: typeof migrations_orgUnits;
  news: typeof news;
  newsSchedule: typeof newsSchedule;
  newsletter: typeof newsletter;
  notifications: typeof notifications;
  offboarding: typeof offboarding;
  onboarding: typeof onboarding;
  organizationJoinRequests: typeof organizationJoinRequests;
  organizationRequests: typeof organizationRequests;
  organizations: typeof organizations;
  "organizations/index": typeof organizations_index;
  "organizations/main": typeof organizations_main;
  orgchart: typeof orgchart;
  overtime: typeof overtime;
  "overtime/index": typeof overtime_index;
  "overtime/mutations": typeof overtime_mutations;
  "overtime/queries": typeof overtime_queries;
  "overtime/settings": typeof overtime_settings;
  pagination: typeof pagination;
  payments: typeof payments;
  "payroll/actions": typeof payroll_actions;
  "payroll/index": typeof payroll_index;
  "payroll/mutations": typeof payroll_mutations;
  "payroll/queries": typeof payroll_queries;
  performance: typeof performance;
  positions: typeof positions;
  probation: typeof probation;
  productivity: typeof productivity;
  projects: typeof projects;
  recognition: typeof recognition;
  recruitment: typeof recruitment;
  recruitmentAI: typeof recruitmentAI;
  recruitmentEmails: typeof recruitmentEmails;
  recurringTasks: typeof recurringTasks;
  reporting: typeof reporting;
  rewards: typeof rewards;
  "schema/ai": typeof schema_ai;
  "schema/aiGovernance": typeof schema_aiGovernance;
  "schema/analytics": typeof schema_analytics;
  "schema/assets": typeof schema_assets;
  "schema/attendance": typeof schema_attendance;
  "schema/automation": typeof schema_automation;
  "schema/backups": typeof schema_backups;
  "schema/billing": typeof schema_billing;
  "schema/calendar": typeof schema_calendar;
  "schema/chat": typeof schema_chat;
  "schema/compensation": typeof schema_compensation;
  "schema/compliance": typeof schema_compliance;
  "schema/conflicts": typeof schema_conflicts;
  "schema/corporate": typeof schema_corporate;
  "schema/departments": typeof schema_departments;
  "schema/documentBuilder": typeof schema_documentBuilder;
  "schema/documents": typeof schema_documents;
  "schema/drivers": typeof schema_drivers;
  "schema/employees": typeof schema_employees;
  "schema/events": typeof schema_events;
  "schema/expenses": typeof schema_expenses;
  "schema/goals": typeof schema_goals;
  "schema/hiringPackets": typeof schema_hiringPackets;
  "schema/index": typeof schema_index;
  "schema/integrations": typeof schema_integrations;
  "schema/landing": typeof schema_landing;
  "schema/landingTexts": typeof schema_landingTexts;
  "schema/learning": typeof schema_learning;
  "schema/leaveSettings": typeof schema_leaveSettings;
  "schema/leaves": typeof schema_leaves;
  "schema/meetingRooms": typeof schema_meetingRooms;
  "schema/meetings": typeof schema_meetings;
  "schema/messenger": typeof schema_messenger;
  "schema/news": typeof schema_news;
  "schema/newsletter": typeof schema_newsletter;
  "schema/notifications": typeof schema_notifications;
  "schema/offboarding": typeof schema_offboarding;
  "schema/onboarding": typeof schema_onboarding;
  "schema/operatorTools": typeof schema_operatorTools;
  "schema/organizations": typeof schema_organizations;
  "schema/orgchart": typeof schema_orgchart;
  "schema/overtime": typeof schema_overtime;
  "schema/payroll": typeof schema_payroll;
  "schema/performance": typeof schema_performance;
  "schema/positions": typeof schema_positions;
  "schema/probation": typeof schema_probation;
  "schema/productivity": typeof schema_productivity;
  "schema/projects": typeof schema_projects;
  "schema/recognition": typeof schema_recognition;
  "schema/recruitment": typeof schema_recruitment;
  "schema/rewards": typeof schema_rewards;
  "schema/scim": typeof schema_scim;
  "schema/security": typeof schema_security;
  "schema/settings": typeof schema_settings;
  "schema/shifts": typeof schema_shifts;
  "schema/signatures": typeof schema_signatures;
  "schema/sla": typeof schema_sla;
  "schema/sso": typeof schema_sso;
  "schema/surveys": typeof schema_surveys;
  "schema/tasks": typeof schema_tasks;
  "schema/tickets": typeof schema_tickets;
  "schema/userProfiles": typeof schema_userProfiles;
  "schema/userSettings": typeof schema_userSettings;
  "schema/users": typeof schema_users;
  "schema/webhooks": typeof schema_webhooks;
  "scim/main": typeof scim_main;
  "scripts/auditTestData": typeof scripts_auditTestData;
  "scripts/cleanupQaData": typeof scripts_cleanupQaData;
  "scripts/cleanupQaResidual": typeof scripts_cleanupQaResidual;
  "scripts/createTestAutomationData": typeof scripts_createTestAutomationData;
  "scripts/createTestTicket": typeof scripts_createTestTicket;
  security: typeof security;
  settings: typeof settings;
  settlement: typeof settlement;
  sharepointSync: typeof sharepointSync;
  shifts: typeof shifts;
  signatures: typeof signatures;
  sla: typeof sla;
  "sso/actions": typeof sso_actions;
  "sso/flows": typeof sso_flows;
  "sso/main": typeof sso_main;
  "sso/protocol": typeof sso_protocol;
  strategyMaps: typeof strategyMaps;
  subscriptions: typeof subscriptions;
  subscriptions_admin: typeof subscriptions_admin;
  superadmin: typeof superadmin;
  "superadmin/accessMatrix": typeof superadmin_accessMatrix;
  "superadmin/accessTokens": typeof superadmin_accessTokens;
  "superadmin/controlCenter": typeof superadmin_controlCenter;
  "superadmin/dbAdmin": typeof superadmin_dbAdmin;
  "superadmin/emergency": typeof superadmin_emergency;
  "superadmin/featureToggles": typeof superadmin_featureToggles;
  "superadmin/gdprToolkit": typeof superadmin_gdprToolkit;
  "superadmin/hub": typeof superadmin_hub;
  "superadmin/impersonation": typeof superadmin_impersonation;
  "superadmin/index": typeof superadmin_index;
  "superadmin/landingEditor": typeof superadmin_landingEditor;
  "superadmin/operatorTools": typeof superadmin_operatorTools;
  "superadmin/operatorToolsInternal": typeof superadmin_operatorToolsInternal;
  "superadmin/organizations": typeof superadmin_organizations;
  "superadmin/search": typeof superadmin_search;
  "superadmin/sessions": typeof superadmin_sessions;
  "superadmin/tempPasswords": typeof superadmin_tempPasswords;
  "superadmin/terminal": typeof superadmin_terminal;
  "superadmin/trash": typeof superadmin_trash;
  "superadmin/user360": typeof superadmin_user360;
  supervisorRatings: typeof supervisorRatings;
  surveys: typeof surveys;
  taskFields: typeof taskFields;
  taskRelations: typeof taskRelations;
  taskStatuses: typeof taskStatuses;
  taskTime: typeof taskTime;
  taskViews: typeof taskViews;
  tasks: typeof tasks;
  telegram: typeof telegram;
  tickets: typeof tickets;
  timeTracking: typeof timeTracking;
  updateSuperadminPlan: typeof updateSuperadminPlan;
  userPreferences: typeof userPreferences;
  userStats: typeof userStats;
  users: typeof users;
  "users/admin": typeof users_admin;
  "users/auth": typeof users_auth;
  "users/index": typeof users_index;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "webhooks/main": typeof webhooks_main;
  "webhooks/protocol": typeof webhooks_protocol;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
